### ISSUE TITLE
Having tabliss just show up on the homepage

### ISSUE THREAD

**Issue by PmmaGit** [joelshepherd/tabliss#109]
Hello,

Is it possible to have tabliss just show up on the homepage instead of the new tab, by keeping Firefox's default new tab, but have tabliss show when you open Firefox?

In other words, is it possible to disable the part of the addon that overrides the new tab page?

I know the intended use is to replace the new tab as whole but that would suit more what i'm looking for.

**Comment by wa4-fearless-otter** [comment]
Set https://web.tabliss.io as homepage?

**Comment by PmmaGit** [comment]
> 
> 
> Set https://web.tabliss.io as homepage?

Oh wow, that's a perfect ideia, thanks!
