### ISSUE TITLE
Use of process.env.* fails API use in development

### ISSUE THREAD

**Issue by mbowcutt** [joelshepherd/tabliss#11]
When running webpack-dev locally, process.env is undefined. Since API keys are stored in this location, they get resolved to null. This causes a black background with Unsplashed enabled, and a completely black screen (requiring a hard reset) with Dribbble enabled.

**Comment by mbowcutt** [comment]
Just kidding - I had to register my own API application and configure it in webpack.config.js

**Comment by joelshepherd** [comment]
Yep that's correct. I now realise I haven't added any instructions for the `.env` file into the read me. I'll get that fixed up 👍

**Comment by joelshepherd** [comment]
I have now added instructions to the read me :)
