### ISSUE TITLE
[Dev] Wiki access for development

### ISSUE THREAD

**Issue by trickypr** [joelshepherd/tabliss#111]
Hi,

I was wondering if the wiki could be opened up as a guide for development and similar things. I think a lot more people would work more on development if there was more information on how to development and style.

**Comment by joelshepherd** [comment]
Hi! Yeah this is a good point. I have lately been quite busy with my regular job, but have been thinking for a while about rearchitecting the plugin structure to make Tabliss easier to develop for.

Specifically, I want to define a stable plugin interface - documenting what props will be passed to your components and how to use them. Possibly use some of React's newer features in there too (like hooks).

Lastly I was to migrate over to prettier to address any code style issues.

**Comment by joelshepherd** [comment]
After thinking about this some more, I am going to create a RFC pull request with my initial thoughts for the redesigned plugin interface. Feel free to add any thoughts on how to make it easier to work with.

I'll link it to this issue once I have created it.

**Comment by joelshepherd** [comment]
See: #115 👌
