### ISSUE TITLE
Safari Support

### ISSUE THREAD

**Issue by itsmejacobw** [joelshepherd/tabliss#112]

**Comment by trickypr** [comment]
The safari extension api is odd. Unlike most extension apis you have to design it with an Apple computer running Xcode and have an Apple developer account to publish it. If you want a fix for this before Apple decides to make their api based on a standard, your best bet is to set your new tab page and home page to the web version of tabliss.

**Comment by joelshepherd** [comment]
Like @trickypr said, Safari extensions are a strange beast and probably nothing I will look to support until the move to the web extensions API.

However @trickypr's solution is a fine workaround to enjoy Tabliss in Safari. I might a link here from the FAQ on the website for people looking for Safari support 👍

**Comment by trickypr** [comment]
I realize this issue has been closed for a while, however apple has announced that they will be switching over to web extensions with the next version of MacOS. There is a [guide](https://developer.apple.com/videos/play/wwdc2020/10665/) releasing tomorrow, but I probably won't be able to look into it until the full release of MacOS 11.
