### ISSUE TITLE
Localization through Google maps

### ISSUE THREAD

**Issue by rafspiny** [joelshepherd/tabliss#122]
**Tabliss version:** 1.17.0

When adding a new `Weather` gadget and looking for a city, the following error happens:
> Unable to determine location. Please try again later.

Apparently, by looking at the inspector, it is trying to use Google maps to get a city and failing for the missing API Key. See picture below.

![Tabliss](https://user-images.githubusercontent.com/1770381/56083867-d794c780-5e2a-11e9-8575-b519728fd106.jpg)

**Comment by joelshepherd** [comment]
This was fixed in #117 and has been released!
