### ISSUE TITLE
"0" character at top left of the screen

### ISSUE THREAD

**Issue by ipproductions** [joelshepherd/tabliss#123]
Firefox: 66.0.2
Version: 1.17.0
Around this area of the code, just before the credit div:

```
<div class="App">
<div class="Dashboard fullscreen booted">
<div class="Unsplash fullscreen">
<div class="image fullscreen" style="filter: blur(5px); transform: scale(1.01); background-image: url(&quot;blob:moz-extension://fc7748f5-8bd7-4db3-bf52-1deec35d313c/da65266c-6754-46e3-ae13-2e2ca8a7dcdf&quot;);"></div>
0
<div class="credit">
```

It only shows through the blur and if you have default Firefox BG set as a dark color, perhaps. The higher the blur, the more it shows.

As a temporary workaround, add custom css widget with code:
```
.fullscreen { color: transparent; }
.credit { color: white !important; }
.Widgets { color: white !important; }
```

**Comment by trickypr** [comment]
I can confirm that this is reproducible by turning darken all the way down. The code that caused this is probably around [line 89](https://github.com/joelshepherd/tabliss/blob/c614c7d2a8e4e3f30c01e096a06097e95c2521b2/src/plugins/backgrounds/unsplash/Unsplash.tsx#L89) in the `unsplash.tsx` file.
