### ISSUE TITLE
[Feature request] Allow darken custom pictures

### ISSUE THREAD

**Issue by Excigma** [joelshepherd/tabliss#142]
I have a slideshow of custom pictures, it should let me darken/blur them as with pictures from unsplash etc.

Anyway, I can manually do it via Custom CSS as so:

`.Image {
    filter: blur(5px)
}`

so why can't I do it in settings (native way instead of css tinkering)?

What I see:
![image](https://user-images.githubusercontent.com/30280397/60804877-ac740700-a1d2-11e9-8ddc-c6438c9dfb33.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/30280397/60804900-bb5ab980-a1d2-11e9-9cea-c181967db3fb.png)

Thanks for the extension, and here's a look at my newtab: :)
![image](https://user-images.githubusercontent.com/30280397/60804938-de856900-a1d2-11e9-8079-3577994f42a3.png)

Windows 10, Mozilla Firefox

**Comment by joelshepherd** [comment]
Coming in Tabliss 2 🎉
