### ISSUE TITLE
Minor issue - Rename swedish translation abbreviation?

### ISSUE THREAD

**Issue by Vecopotryx** [joelshepherd/tabliss#152]
After having the translation I added merged into the project I saw that it was now named under the name SV instead of SE. I'm not completely sure how the languages are named, but I believe it might be the country codes. Whether or not it is the country codes or just an abbreviation for the name of the language, I'm just worried that it might become a potential issue if someone wants to add a language like Slovakian as I believe that it would have the abbreviation SV. Again I might be wrong but just so thought it would be best to raise this issue. 

Also another minor issue that I found, which is such a small one that I don't think deserves it's own post under issues, is that the translation credit for the swedish translation has an extra space at the end within the quotes. I'm just worried that this might cause the text to not be correctly centered. So it might be worth removing that space if it causes any problem.

Thanks for developing this great extension :)

**Comment by Smile4ever** [comment]
The country code of Sweden is indeed "SE" (or SWE) but the language code for Swedish is SV.

Please consult the ISO 639-1 list with popular 2-letter language codes:
http://www.constitution.org/lg/languagecode.html

There is also a list for countries:
https://www.iban.com/country-codes

As for the space, that can be corrected.

**Comment by Vecopotryx** [comment]
Ah ok, thank you for clearing that up. I'll close this issue and make a pull request for fixing the space 👍

**Comment by Smile4ever** [comment]
No problem.

**Comment by joelshepherd** [comment]
As @Smile4ever said, Tabliss indeed uses the language codes, not the country codes. So I just did a quick rename - no problem.

**Comment by Smile4ever** [comment]
@joelshepherd You confuse me, what did you rename?

**Comment by joelshepherd** [comment]
I was just letting @Vecopotryx know I was the one that renamed his translations from `se` to `sv`.
