### ISSUE TITLE
[Feature Request] Use cards to configure widgets

### ISSUE THREAD

**Issue by trickypr** [joelshepherd/tabliss#154]
Hi, 

I was wondering if widget settings could be put on [cards](https://material.io/design/components/cards.html) that can be dragged around as part of the improvements to the setting UI with Tabliss 2. HTML5 offers a [drag and drop api](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API) that could prove helpful. The [material ui](https://material-ui.com/) library provides a good react [card component](https://material-ui.com/components/cards/) that maybe helpful.

**Comment by joelshepherd** [comment]
Hm, is this so you can adjust widgets that are behind the current setting plane and still see the changes?
