### ISSUE TITLE
On Chrome, tabliss with large amount of images corrupts other settings.

### ISSUE THREAD

**Issue by JamesG269** [joelshepherd/tabliss#155]
This manifests as my quick links disappearing and becoming corrupted. I have around 500 1080p+ images. This works fine in firefox however.

**Comment by joelshepherd** [comment]
Hm, Firefox and Chrome do have different limits to the maximum amount of data an extension is allowed to store. I have a feeling you may be hitting this, and unfortunately I cannot do anything about this limit.

As a side note - I'm actually quite surprised Firefox even lets you get 500 images in there! How is the start up performance of Tabliss? (ie, the time between opening a new tab, and Tabliss loading. Is it still under a second?)

**Comment by JamesG269** [comment]
Firefox loads quick as it does with as without the images. Work fine, no issues.
