### ISSUE TITLE
[Feature Request] Back up of initial setup configured 

### ISSUE THREAD

**Issue by AshokRaja10** [joelshepherd/tabliss#158]
I have set up multiple Quick Links in my laptop Firefox browser. Now when I opened Firefox on my desktop and logged into my Firefox account, all the setup that I have done on tabliss is lost.

It would be ideal if all the setup configured in tabliss is backed up in my Firefox account and thus making, switching between devices seamless by totally avoiding the initial setup.

**Comment by joelshepherd** [comment]
Hi! This feature is coming to Tabliss 2 in the next few weeks. Your Tabliss settings will automatically sync with your Firefox account!
