### ISSUE TITLE
Certain images cause the credit text to become very hard to see

### ISSUE THREAD

**Issue by bxio** [joelshepherd/tabliss#159]
When tabliss picks images of snow, such as [this](https://unsplash.com/photos/QFgPjdGfpfE), the text that usually displays at the bottom left of the image becomes invisible as it is the same colour as the image. 

To correct this, we should either add a border to the text, or add a light background to the text area. We could also vary the colour of the text and icons based on the dominant colour of the background image.

**Comment by Smile4ever** [comment]
We could also add a light background only on hover.

**Comment by bxio** [comment]
Closing this issue as it's basically the same as #121
