### ISSUE TITLE
URL enconding for the Search Box widget

### ISSUE THREAD

**Issue by Thanaen** [joelshepherd/tabliss#160]
Hi,

It seems that the search box widget doesn't encode the search query, which seems to break some search engines (like Qwant).

It's quite easy to reproduce:

1. Set the Search Box widget to use Qwant
2. Type "c# console wait for input" and press enter
3. See that Qwant only shows results for the query "c" (because the # character hasn't been encoded, which makes the rest of the query being ignored)

If I type the encoded Query in the input field (c%23%20console%20wait%20for%20input), it works fine.

I would like to help you solve this issue, if necessary. ~~(However, I don't know where the widget code is located 😅)~~ *Found it!*

***
Browser: Firefox 69.0
Extension: Tabliss 1.18.2

**Comment by Thanaen** [comment]
See #161

**Comment by joelshepherd** [comment]
Thanks for finding and fixing this! It will be out in the next release! 👌
