### ISSUE TITLE
[Meta] Run automated tests with Travis CI

### ISSUE THREAD

**Issue by Thanaen** [joelshepherd/tabliss#162]
Hi,

Maybe it could be useful to add [Travis CI](https://travis-ci.org/) to this repos (or any other testing bot) in order to automatically run the `npm test` command every time this repos receives a Pull Request or a push to master! It probably would lighten up your Pull Request testing routine!

What are your thoughts about this?

**Comment by joelshepherd** [comment]
Hello!

Tabliss currently uses circleci to run `npm test` on each build.
See: https://github.com/joelshepherd/tabliss/blob/master/.circleci/config.yml

Although I think I'd like to swap that out to try GitHub actions in the near future! But that's future Joel's problem :joy:

Thanks for reminding me though!
