### ISSUE TITLE
[Feature Request] World Clock

### ISSUE THREAD

**Issue by jwhayman** [joelshepherd/tabliss#168]
Hello. Firstly, thank you for creating Tabliss. I'm really enjoying using it.

I'd like to propose a world clock feature with the following features:

- Add and display times for different cities/timezones
- Ability to add multiple cities/timezones
- Date format based on the "time" widget settings
- Custom positioning, left, right, top, bottom centre, vertical, horizontal

Example attached:
![image](https://user-images.githubusercontent.com/1651421/64593198-d8308a80-d3d7-11e9-86b1-81ec45186ef7.png)

**Comment by gonzalrick** [comment]
Hi @jwhayman, this feature went live with the version 2.1.0 release. Thanks!
