### ISSUE TITLE
[Bug] Can't open websites in Firefox Nightly 71.0a1 (2019-09-10)

### ISSUE THREAD

**Issue by entepe85** [joelshepherd/tabliss#169]
**Steps to reproduce**

- Open a new tab when Tabliss is enabled
- Try opening a website through the URL bar

**Expected result**
The website should be openend

**Actual result**
The tab immediately closes and the previously active tab becomes active again

I have already [filed a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1580418) for this behaviour with the Firefox devs.

**Comment by entepe85** [comment]
Closing this - it seemed to be some arbitrary issue related to my profile and does not occur with a fresh profile.

**Comment by joelshepherd** [comment]
I hadn't seen that before. Glad you got it resolved!
