### ISSUE TITLE
Recently Closed Tabs

### ISSUE THREAD

**Issue by Qwash** [joelshepherd/tabliss#17]
New empty tabs are stored in Recently Closed Tabs menu
This makes Ctrl+Shift+T much less effective

**Comment by joelshepherd** [comment]
Hmm, that's true. I'm not 100% positive that is something I can change (it might be intrinsic to the browser), but I'll look into it!

**Comment by tjvf** [comment]
You can use [sessions.forgetClosedTab()](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sessions/forgetClosedTab) for that (currently Firefox 55+ only). 

This doesn't remove the pages from history, just recent tabs. Removing them from history would require the history permission.

**Comment by Smile4ever** [comment]
I have filed a bug for it: https://bugzilla.mozilla.org/show_bug.cgi?id=1446912

**Comment by joelshepherd** [comment]
After much deliberation (I kid :joy:), rather than adding the `session` or `history` permissions to workaround the issue, I will leave this bug to the Firefox team. I try and keep Tabliss as permission free as possible.
