### ISSUE TITLE
Search widget truncates search terms at octothorpe (#) character

### ISSUE THREAD

**Issue by hravnx** [joelshepherd/tabliss#178]
To reproduce:
  1. Ensure the search widget is added to your tab
  2. Type in the following search terms (without the quotes) "C# code gen" and hit enter

Expected result:
  A search for C# code gen

Actual result:
  A search for C

**Comment by trickypr** [comment]
This has been fixed by #161, but that fix hasn't been released yet. Thanks for the issue though.

**Comment by hravnx** [comment]
Any idea of when it will be released?

**Comment by trickypr** [comment]
Not entirely sure, but you can see the progress on its [project page](https://github.com/joelshepherd/tabliss/projects/1).
