### ISSUE TITLE
Allow some widgets added more than a single time

### ISSUE THREAD

**Issue by Zocker1999NET** [joelshepherd/tabliss#184]
Allowing multiple widgets of the same type would increase the usability of the page significant.

For example I wanted to see quotes from two different sources however I could not add the quotes widget twice. Or If some wants to see the weather from two different locations at the same time.

I hope the architecture allows this.

**Comment by trickypr** [comment]
This is a feature coming to Tabliss with Tabliss 2 🎉! We just need to get it released. I have no clue when it will be released.

**Comment by joelshepherd** [comment]
Hello, as @trickypr has said, this is coming in Tabliss 2. I was pulled off Tabliss for quite some time by some other projects. However, I have some time over the Easter weekend and am hoping to get it released during the course of it!
