### ISSUE TITLE
[Feature Request] Tabliss as homepage -> focus address bar

### ISSUE THREAD

**Issue by h4rp00n33r** [joelshepherd/tabliss#185]
Hey Joel,

thanks for this great addon!

Tabliss opens when I start Firefox. I'd like Tabliss to focus the adress bar direct after the startup. This works with new tabs perfectly but not with Tabliss as a start page...

Greetings from Germany
Marc

**Comment by hematogender** [comment]
Clone of #137 
Answered your question there.

**Comment by Evpok** [comment]
@hematogender Actually this is the opposite issue: currently, when opening Tabliss, the focus is on the search bar widget if there is one, but if there is none, the address bar is *not* focused, which is one more click to search when opening a new tab.

**Comment by joelshepherd** [comment]
Seems to be working correctly now. I believe this was a Firefox bug originally.
