### ISSUE TITLE
Literature Clock ignores Timezone Settings

### ISSUE THREAD

**Issue by xoir** [joelshepherd/tabliss#187]
![Bildschirmfoto von 2019-12-30 00-58-48](https://user-images.githubusercontent.com/14925165/71564349-49836e80-2a97-11ea-9bdc-2942433fed1a.png)

Tested on Waterfox Current (2019.10) based on Firefox 68 ESR.

**Comment by xoir** [comment]
The same is happening in Firefox 71 and Chrome 79. The Digital Clock widget follows the timezone settings. The literature clock does not.

**Comment by trav-i** [comment]
seconding this, same issue in firefox 74. Reproduced just like the above screenshot.

**Comment by joelshepherd** [comment]
Hey guys, this has been fixed in the coming Tabliss 2 release. Thanks for pointing this out!
