### ISSUE TITLE
Tabliss Dockerfile

### ISSUE THREAD

**Issue by deadbird99** [joelshepherd/tabliss#188]
Hi!

First, thanks for the great work you're doing on Tabliss!

I'm currently trying to dockerize the app in order to self host it and enjoy it from desktop computer, tablet, smartphone and so on. I'm also willing to publish the image when it works fine.

I'm not very fluent with dockerfiles, and so far I couldn't produce a viable container. Producing the image seems ok, but when I create a container from it, it crashes right after starting...

My dockerfile:

```
FROM node:latest
WORKDIR /usr/src/tabliss
EXPOSE 8080
RUN git clone https://github.com/joelshepherd/tabliss /usr/src/tabliss
RUN npm install
RUN npm run build
```

And here is the full log: [log.txt](https://github.com/joelshepherd/tabliss/files/4042599/log.txt)

Can someone help?

Thanks in advance.

**Comment by trickypr** [comment]
Quickly scanning through that log it seems like it successfully built. I think that your issue is that there is no web server running. For more info see the react [deployment](https://create-react-app.dev/docs/deployment/) docs. 

/side note/
Master has the unstable code for v2. We would love people testing it.

**Comment by deadbird99** [comment]
Hi,
Upon further investigation, I made great progress and now I think the issue may come from tabliss itself. Here's why.

I successfully create a stable container using this dockerfile:
```
FROM node:latest
WORKDIR /usr/src/tabliss
RUN git clone https://github.com/joelshepherd/tabliss /usr/src/tabliss
RUN npm install
RUN npm run build
CMD [ "npm", "start" ]
EXPOSE 8080
```

From here, when the container is up and running, if I use `docker exec -it mycontainer curl http://localhost:8080`, I get a response *from within* the container.
But if I do `curl http://localhost:8080` from *outside* the container, I get an empty reply.

Is there a way tabliss serves `127.0.0.1` only instead of `0.0.0.0` ?

**Comment by deadbird99** [comment]
Hi!

I made some progress, and I was able to start a container with this dockerfile:

```
FROM node:latest
WORKDIR /usr/src/tabliss
EXPOSE 8080
ENV PATH /usr/src/tabliss/node_modules/.bin:$PATH

RUN git clone https://github.com/joelshepherd/tabliss /usr/src/tabliss
RUN npm install
RUN npm run build
CMD [ "npm", "start" ]
```

But once launched, any `http://containerip:8080`  request results in a timeout.

Any docker-guru help is appreciated...

**Comment by deadbird99** [comment]
Ok, I finally found the solution, thanks to [a reddit user](https://www.reddit.com/r/docker/comments/eomcrb/curl_timeout/).

I also had to add `--public myhostname`, so now I can't provide an image as it contains my custom hostname.

So! The Dockerfile is the following:

```
 FROM node:latest
WORKDIR /usr/src/tabliss
EXPOSE 8080

RUN git clone https://github.com/joelshepherd/tabliss /usr/src/tabliss
RUN sed -i 's#"start": "webpack-dev-server"#"start": "webpack-dev-server --host 0.0.0.0 --port 8080 --public YOUR.DOMAIN.TLD"#g' package.json
RUN npm install
RUN npm run build
ENV PATH /usr/src/tabliss/node_modules/.bin:$PATH
CMD [ "npm", "start" ]
```

With `YOUR.DOMAIN.TLD` to be changes to whatever your domain is. Please consider adding these infos to tabliss' repo so we can all enjoy a self-hosted version.
