### ISSUE TITLE
Set tabliss only as homepage

### ISSUE THREAD

**Issue by DonKannalie** [joelshepherd/tabliss#193]
Is it possible to set tabliss only as homepage? I want another extension to manage new tabs.

**Comment by Smile4ever** [comment]
Set https://web.tabliss.io/ as your homepage.

**Comment by DonKannalie** [comment]
I meant !only! As home page. I want to use GroupSpeedDial as new tab. Tabbliss overrides its new tab feature (GroupSpeedDial is normally set as new tab, but with tabliss its overridden, even when I activate GroupSpeedDial after tabliss).

**Comment by Smile4ever** [comment]
You uninstall Tabliss and set your home page to https://web.tabliss.io.

**Comment by DonKannalie** [comment]
Oh boy, yes, thank you. I am an idiot.

**Comment by Smile4ever** [comment]
@DonKannalie Please close this issue if the solution is good for you.
