### ISSUE TITLE
Local web page version

### ISSUE THREAD

**Issue by Jemi** [joelshepherd/tabliss#194]
It would be nice if you could make a local webpage version of tabliss. The reason I became interested in tabliss was because extensions don't work on certain pages, such as the about:newtab page. But evidently extensions don't work on an extension's new tab page either. A downloadable web page version of tabliss could solve this problem, while still keeping all of the tabliss functionality.

**Comment by joelshepherd** [comment]
Hello, what exactly do you mean by download the webpage? I suppose if you go to https://web.tabliss.io and pressed "control + s" it would save the webpage locally. Tabliss doesn't use any special permission so it should work mostly correctly.

Does that cover what you are looking for?
