### ISSUE TITLE
Show a specific collection

### ISSUE THREAD

**Issue by bitboxer** [joelshepherd/tabliss#2]
I would love to be able to show photos of a specific collection, [this one](https://unsplash.com/collections/410546/the-road-less-travelled) for example.

**Comment by joelshepherd** [comment]
That's a great idea! I'll see about adding it in the next release.

**Comment by joelshepherd** [comment]
Got around to it quicker than I though. A new version was just released that includes the ability to filter Unsplash by custom collections.

It is a bit rudimentary at the moment, but you just need to paste in the collection ID number. You can find this number in the URL when you're viewing a collection. In your case, its `410546`.

Just a quick tip (for anyone else who comes across this either), you can specify multiple collections by comma separating the collection IDs. For example, `410546,1173341`.

And yes, I'll come up with a friendlier method of inputting collections in the future :joy:

**Comment by bitboxer** [comment]
Awesome. Thank you for this.
