### ISSUE TITLE
Extension for the new Microsoft Edge

### ISSUE THREAD

**Issue by brcmesquita** [joelshepherd/tabliss#201]

**Comment by joelshepherd** [comment]
Hm, this could be on the cards now it's based on Chromium. I'll have a look into it.

**Comment by trickypr** [comment]
The chromium version of tabliss worked with edge when I tested it a month or so ago. Also, there is a nice guide for how to [apply](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension).

**Comment by Nedlinin** [comment]
Just another confirmation that installing directly from the Google Web Store works great in the newest Edge.

**Comment by brcmesquita** [comment]
> Just another confirmation that installing directly from the Google Web Store works great in the newest Edge.

That Cool! I took the test here and managed to install it through the Chrome store, not only Tabliss, but it is also possible to install other extensions. Thanks for the tip! He ended up helping me with other things too!
