### ISSUE TITLE
Time widget has bold instead of slim font weight

### ISSUE THREAD

**Issue by wasdennnoch** [joelshepherd/tabliss#210]
First off, thank you for maintaining this awesome plugin!
I just updated to Tabliss 2.0.0 and immediately noticed that the Time widget now has bold text instead of the previous slim font weight.
Using the inspector it seems that the correct `font-weight: 400;` is set on the `.Widget` wrapper but the browser-integrated stylesheet overrides it further down the line for the `h1` element containing the actual text with the default `font-weight: bold;`.
Same thing happens for the `font-size` property, but since the user-agent stylesheet sets it to `4em` the custom config value it just multiplied by 4 (or however that calculation works).
I'm using Chrome 80.

**Comment by trickypr** [comment]
From what I can tell, the multiplication of font sizes is intentional. It means that there is a difference in size between `h1`, `h2`, `h3`, etc. This way if you have a widget with a `h1` and a `h2` you will be able to tell them apart.
