### ISSUE TITLE
Background Images don't fade in smoothly anymore in Tabliss 2

### ISSUE THREAD

**Issue by wasdennnoch** [joelshepherd/tabliss#211]
Previously in Tabliss 1 when you opened a new tab the background image quickly faded in. This covered up the short loading time.
Now in Tabliss 2 when I open an new tab (or refresh) there is a short moment in which the image isn't loaded from storage yet, resulting in a few frames of solid black until suddenly the image appears. Or, if you spam-refresh the tab to find a nice image (am I the only one :D) it doesn't seem as smooth anymore as it was before.
This issue is basically the opposite of #67 which requested the exact opposite - removing the fade.
Using Chrome 80.

**Comment by joelshepherd** [comment]
Oh yeah, I forgot to add the fade back in :facepalm:

I think I good compromise may be a faster fade, say ~50ms. I'll see what I can do.

**Comment by joelshepherd** [comment]
Coming back in next patch with a slightly faster animation this time. Plus the widget now still show up instantly to improve the speed feel.
