### ISSUE TITLE
Another quick link alignment issue in 2.0.2

### ISSUE THREAD

**Issue by RainerZufahl** [joelshepherd/tabliss#216]
Hey,

another person brought an alignment issue to your attention, but that solution doesn't seem to have solved what I'm encountering. 

I have 3 quick links set up in one row, all of them with icons. When they are aligned in the center, the separate icons have their anchor point to the left, until a certain scale is reached. When aligning them anywhere else, they scale from the middle of the group (as is expected).

Here's a gif:

![2020-04-14_17-57-04](https://user-images.githubusercontent.com/18621898/79246301-78bcc080-7e79-11ea-8707-c141d65d0d72.gif)

I suppose this is a simple container issue, but I could be totally wrong. Would love to see this fixed, but it's nothing that needs to be done asap.

**Comment by joelshepherd** [comment]
Ah I see what the issue is. I'll fix this in an upcoming patch :)

**Comment by RainerZufahl** [comment]
The issue still isn't fixed for me, looks just like before the 2.0.3 update. I've checked that Firefox is running the 2.0.3 version, and the Tabliss web version (which I expect to be on the latest version) also shows the issue.

**Comment by joelshepherd** [comment]
Hello, I have made the fix in master, but it hasn't been released in a fix yet. There is 1 or 2 other bugs I want to fix first.

You can check it out on the beta link to see the fix in action: https://tabliss-beta.s3-us-west-2.amazonaws.com/index.html
