### ISSUE TITLE
[Firefox] New Tab doesn't restore on restart

### ISSUE THREAD

**Issue by afnkhn** [joelshepherd/tabliss#22]
Steps to reproduce:

1. Open some websites in Firefox
2. Open a single new tab. Make sure its the last tab
2. Press Shift + F2
3. Type restart and press Enter

Actual results:

After restart new tab is missing

Expected results:

New tab should not be missing

This also happens when restarting Firefox for update

**Comment by joelshepherd** [comment]
Hmm, I can reproduce it, but it seems that Firefox treats the newtab page as a sort of disposable (system?) page and doesn't remember it when restarting. Another way to demonstrate this "disposable" trait is to open the "Options" menu while your on a newtab page. You will see your newtab (in this case, Tabliss) gets replaced with the options page. Alternatively, if you do this when your are on a regular website, the options menu is opened in a new tab instead.

As such it seems as if its a feature of Firefox. I also cannot think of anything that will let me change how sessions are restored sorry.

I think you will need to log this as a bug with Firefox (specifically, newtab pages not restored with session). I'll close this for now, but if anyone has another solution, or Firefox changes something that gives me control of the issue, I will gladly reopen this for you.
