### ISSUE TITLE
new background every second instead every 15 minutes

### ISSUE THREAD

**Issue by kyrawertho** [joelshepherd/tabliss#223]
Hi,

Tabliss upgraded itself today (2.0.2) and it asked me to migrate my settings. It is now displaying an incorrect time (2 hours difference when timezone is set to Automatic).

When I select the correct timezone, the page starts refreshing every second, changing to a new background image every second refresh. I want to see a new image every 15 minutes, but the same happens when I select every 5 minutes or every hour.

I have reinstalled Tabliss and reset settings to default but this makes no difference. Only when I select any timezone that happens to be -2 hours the flashing stops.

**Comment by terrypa** [comment]
I had the same issue, i did not reinstall i simply change refresh time from 15 to other few times and afther that it wroked fine

**Comment by joelshepherd** [comment]
Oh interesting. I have had a few people report this, but I have been unable to replicate it. I'll try playing with the time zone, maybe some interaction between custom time zones and the cache is broken. :thinking:

**Comment by joelshepherd** [comment]
I can confirm that does indeed break it :facepalm: :joy:

I'll see if I can fix this ASAP!
