### ISSUE TITLE
Font Size in 2.0

### ISSUE THREAD

**Issue by rteshnizi** [joelshepherd/tabliss#226]
I'm pretty sure there was an easy way in the GUI to increase/decrease the font size in version 1 using plus/minus buttons.

There is an option to set the font-family per widget in 2.0. It would be nice if you add a font-size per widget as well.

**Comment by joelshepherd** [comment]
Hello! The font-size moved to just "size" under "Display Options", as it also adjusts the size of other elements in the widget too.

**Comment by devisions** [comment]
But it looks like that "Display Options" disappeared nowadays. 🤔 

![image](https://user-images.githubusercontent.com/14140226/80305422-2ce91000-87c5-11ea-86aa-27325a073a78.png)

**Comment by trickypr** [comment]
Display settings are widget specific. 

<img width="375" alt="Screenshot 2020-04-27 at 8 53 56 am" src="https://user-images.githubusercontent.com/23250792/80321979-ecd96a00-8864-11ea-8672-f9d71f668f0c.png">
