### ISSUE TITLE
Lost config with Firefox Multi-Account Containers

### ISSUE THREAD

**Issue by BenceSzalai** [joelshepherd/tabliss#230]
If using Containers in Firefox and Tabliss is configured in the main container, opening a tab in another container prompts with the same message that showed up after v2 update. But in this case if I click on [Migrate your old settings], my settings are reset*, for all Containers. To keep the settings from the main container I have to click on [Delete and start fresh].

(*: I don't know if reset to default or reset to the active Container's settings, because I only have my settings customised in my main Container, as Tabliss behaves the same as in my main Container in all Containers, and I'm happy with that.)

Based on the behaviour my guess is that Firefox loads the plug-in settings from the main Container, regardless of the actual Container, but Tabliss, when checking for the version of the configuration hits the Container's own separate storage. When I click [Migrate...] therefore it reads the settings from the actual Container but unfortunately in turn it overrides the settings in the main Container and therefore in all Containers. Clicking on [Delete and start fresh] for some reason leaves the settings as they are and I can move on.

Unfortunately I had to restore my Firefox settings from offline backup, because after the first question and clicking on [Migrate your old settings] my Tabliss settings were gone without an option to Undo the reset.

**Comment by mpdeimos** [comment]
Same here, lost the config. Is there a way to recover it from preferences?

**Comment by BenceSzalai** [comment]
If my guesses above about the root cause are true, it's most likely impossible to recover the old settings, unless you have a backup of the Firefox profile folder (which I find many times useful, last time when due to a bad release FF decided to uninstall bunch of my plug-ins thinking there was a certificate issue).
You may be out of luck this time, but start making backups so you'll be in better position the next time.
Still, the devs may know a way to recover old config, if it is saved anywehere...

**Comment by qcz** [comment]
Same problem here. Very annoying.

**Comment by LongJohn-Silver** [comment]
How do you add Tabliss to a container? I'm struggling because I use both MAC and TC and whenever I do a search on Tabliss it opens another tab (so I have the tab from Tabliss and the tab from my search engine because TC opens a new one since the previous wasn't isolated). I tried to fix this by creating a MAC container labeled "Search" but I can't add Tabliss to it.

**Comment by dpalacio** [comment]
Here in Firefox ESR 78.8 I don't lose my settings when I open Tabliss in a container. But I do lose the manually uploaded background images, leaving me with a solid dark background.

**Comment by joelshepherd** [comment]
This has been fixed about a year ago, and the manually uploaded images should be fixed as of 2.2.0!
