### ISSUE TITLE
Time breaks free from the 24 hour limit

### ISSUE THREAD

**Issue by wasdennnoch** [joelshepherd/tabliss#231]
![image](https://user-images.githubusercontent.com/10065021/79672982-c2d5d700-81d6-11ea-9ca2-611830120ee5.png)
Only happens at 00:XX.
Chrome 81.

**Comment by trickypr** [comment]
tl;dr: new standard is a bit wonky

**Slightly longer**
There is a new web standard only implemented by chrome. This standard has `hour24` and `hour23` in it. `hour24` goes from 01 - 24, `hour23` goes from 00 - 23. I will look into writing a work around.

**Comment by nstrelow** [comment]
Is this fixed?
I only realized this 24:xx bug today.

Using Chrome Dev Version 89.0.4356.6 (Official Build) dev (64-bit)

**Comment by trickypr** [comment]
I don't believe that this bug fix has been released yet.

**Comment by nstrelow** [comment]
@trickypr Thanks for informing me.

@joelshepherd Could you release a new version please? Thanks a lot :)

**Comment by trickypr** [comment]
Should be fixed by 2.1.0
