### ISSUE TITLE
Upgrade path using multiple devices

### ISSUE THREAD

**Issue by tribut** [joelshepherd/tabliss#234]
When upgrading to tabliss2, the user is offered the choice between "migrate config" and "use default". From what I have seen, both buttons seem to overwrite the already synced config for all other devices. Restarting and re-syncing several times before clicking any of the buttons did not make this screen go away.

**Comment by tribut** [comment]
Possibly related to #230, but I am not using account containers.

**Comment by joelshepherd** [comment]
Sorry this was an oversight of the v2 update :(
