### ISSUE TITLE
[question/suggestion]

### ISSUE THREAD

**Issue by diksown** [joelshepherd/tabliss#238]
first of all, I would like to say that this extension is truly awesome and beautiful, and my favorite part is that it is highly customizable too.
well, I wanted to know if there is a way to save my settings, since I've done some modifications and it always take me some time to reproduce them in another computer.
if not, I would like to suggest that if possible :)
there could be an option to save the settings to a file (or even having an account linked to tabliss)

**Comment by trickypr** [comment]
This issue is a duplicate of #165.

Tabliss has a function where you can sync settings across different devices using a firefox or google account. It would be an interesting feature in terms of sharing configs.
