### ISSUE TITLE
Textbox widget

### ISSUE THREAD

**Issue by dufferzafar** [joelshepherd/tabliss#240]
I find the todo widget too much for my use case. 

Adding a simple textbox widget, that I can add text in would be great!

**Comment by trickypr** [comment]
How would it be different from the message widget? Would it just be a message widget that you could edit as part of the dashboard rather than needing to open up settings?

**Comment by dufferzafar** [comment]
Yeah, exactly!

**Comment by trickypr** [comment]
Should be possible. I will take a look into it.

**Comment by trickypr** [comment]
I miss read some of the code. I would have to muck with redux, which I don't no how to work with. For any other programmer who wants to look into this, [`contenteditable`](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content) allows you to edit any element with no changes to style.

**Comment by joelshepherd** [comment]
Textbox/Notes widget coming in the next release :)
