### ISSUE TITLE
Syncing with Syncthing (Where is the tabliss folder located?)

### ISSUE THREAD

**Issue by VINTX2** [joelshepherd/tabliss#243]
Hello,
I want to sync my settings with Syncthing (offline syncing).
To do this, I need to know where the tabliss settings are stored on Linux. I could only find a .xpi file

Is it even possible to sync this way?
Copying the .xpi file to another profile did not work.

Thank you!

Edit: Copying the whole firefox folder works.

**Comment by trickypr** [comment]
If you want to try a slightly more focused approach, the storage folder *should* contain a folder with the same name as the addon id you can find this by opening the setting, scrolling down and opening "open when firefox starts"). inside of `[profile dir]/storage/default` there should be a folder with the same id as the addon id. 
I don't know how firefox handles addon ids so this may or may not work.

**Comment by mikail0** [comment]
Thanks.
I can see in that folder that Firefox stores addons as SQLite databases.
So there is the same problem as with syning bookmarks with Syncthing.
(syncing databases is a problem in general)

I read on reddit that syncing databases is possible, when Firefox is closed. I need to try that out.
