### ISSUE TITLE
Clock does not display time properly while using the 24 hour display format

### ISSUE THREAD

**Issue by denis-onder** [joelshepherd/tabliss#244]
Browser: Chrome v.81.0.4044.138
Time display format: 24 hour

The time is not being displayed properly, as in that instead of showing 00:00 when the time reaches midnight, the time displayed is 24:00

![Image](https://i.imgur.com/sxK1KFK.png)

**Comment by trickypr** [comment]
**tl;dr** Chrome broke stuff, we fixed it, but the update hasn't come out yet.

The original issue is #231. The pull request with more technical details is #233. This should be fixed with the release of `2.0.4` but I don't know when that will happen.
