### ISSUE TITLE
 [Feature Request] Allow for toggling off "AM/PM" when using 12 hour time format

### ISSUE THREAD

**Issue by goodwinchris** [joelshepherd/tabliss#247]
I imagine a checkbox in the sidebar allowing for a user to disable AM/PM is all this would require.

**Comment by goodwinchris** [comment]
After digging into this a bit, it appears the call to format the time `const formatedTime = Intl.DateTimeFormat(locale, options).format(time)` doesn't allow you to pass any kind of information to remove the `AM` or `PM` dayPeriod. If someone knows how to do that I'd love to hear how.

**Comment by trickypr** [comment]
From what I can find, there is no way to control that part of the output from `Intl.DateTimeFormat`. The way I would do it is just remove the AM and PM using `string.replace()`. I will look into implementing it.

**Comment by goodwinchris** [comment]
@trickypr my biggest concern was language and translation. If we are searching only for a string like `AM` or `PM` then we may not build a feature that works correctly with other languages.

**Comment by trickypr** [comment]
I didn't think of that. It may just be a waiting game to see if there is a library out there that handles it or if it is added to the spec in future versions.

**Comment by goodwinchris** [comment]
The only thing I could find was `.formatToParts` but I'm not skilled enough with JS to feel confident about using it.

**Comment by trickypr** [comment]
That works. [Here is an example](https://jsfiddle.net/59posza3/15/). I will create a pull request when I get some time.

**Comment by goodwinchris** [comment]
This looks super promising! Thank you!
