### ISSUE TITLE
css adds in prefs

### ISSUE THREAD

**Issue by GrosBourrin** [joelshepherd/tabliss#248]
I don't know if it's the right place to ask that, but how to tweak tabliss with custom css or js  in the side-box preferences ? what are the id's of the elements? you add this box to tweak tabliss but i can't find a place or forum to learn how to do this !

**Comment by trickypr** [comment]
There is no documentation about customizing tabliss currently. This is because there is no standard method of customizing tabliss. If you want to customize tabliss, you need to poke around in the inspector and find what you want to customize it.

**Comment by GrosBourrin** [comment]
ok :) thanks for reply

**Comment by Staubgeborener** [comment]
Also take a look to some examples like [this](https://gitlab.com/-/snippets/2009089) one here. Pretty self-explanatory.

**Comment by iTouchU** [comment]
Yes, I found this example that you linked, but as I asked there, how do we target an uploaded image so we can resize it? so the browser header doesn't cut the top of the image off?

**Comment by jordles** [comment]
> Yes, I found this example that you linked, but as I asked there, how do we target an uploaded image so we can resize it? so the browser header doesn't cut the top of the image off?

In case anyone is still wondering how to target uploaded images: When you inspect the image itself, it uses the background property and has 'Image' class attached to all images.
