### ISSUE TITLE
[firefox] Focus on the Awesomebar when new tab is created

### ISSUE THREAD

**Issue by mostlygeek** [joelshepherd/tabliss#25]
The default new page puts the focus on the Awesomebar when a new tab is created. Could Tabliss do the same thing?

**Comment by joelshepherd** [comment]
Hi! Tabliss is setup to focus the awesomebar by default when you open a new tab.

However, are you on Mac by any chance? There is currently a bug that I know about, where if you are running Firefox in Mac's fullscreen mode (by pressing the green expand button), the awesomebar does not get focused when you create a new tab. Unfortunately this instance is a bug in Firefox itself and is completely beyond my control :(

**Comment by mostlygeek** [comment]
Thanks! 

It appears this bug is fixed on both Beta / Nightly now. When I create a new tab the awesomebar gets focus :)

**Comment by mostlygeek** [comment]
I filed a bug for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1434275

**Comment by joelshepherd** [comment]
Hi, thanks for logging this to the bugzilla for me! I only recently discovered the exact cause and hadn't done so yet (+ I get lost in bugzilla).

**Comment by mostlygeek** [comment]
Please add any debugging/cause issues that might help the webextensions to the bug.

**Comment by precz** [comment]
This is not an fix but you could `Ctrl+K` to focus Awesomebar when new tab is created. [Keyboard shortcuts](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly)

**Comment by vorou** [comment]
Fixed in Firefox 61.

After reading through all the threads it turned out I only had to restart my browser to fix it as update was downloaded already : )
Thanks @mostlygeek for reporting it to Firefox guys!

**Comment by joelshepherd** [comment]
I can also confirm this now works in Firefox 61. Thanks again @mostlygeek for championing that fix!
