### ISSUE TITLE
tabliss not working on browser launch

### ISSUE THREAD

**Issue by Advitya-sharma** [joelshepherd/tabliss#255]
Don't know why tabliss is not working when I open browser for first time, it starts working when I open new tab.

- bug in firefox

**Comment by Kalovelo** [comment]
Hello, tabliss has to be manually set as the homepage. This can be done by going to 
Settings>Preferences>Home.

Now change the Homepage and new windows to Custom URLS...
An option with text 'Use current pages' should appear.
Close every tab EXCEPT the tabliss homescreen and then choose the option.

The reason you should close the other tabs is to prevent the homescreen to be a set of tabs.

**Comment by Advitya-sharma** [comment]
solved, but it does not looks good though. @Kalovelo
