### ISSUE TITLE
Enhancement Request: backup/restore

### ISSUE THREAD

**Issue by mbierman** [joelshepherd/tabliss#257]
I would love to be able to backup all my settings and upload them at will. Would be useful in: 

- Setting up new devices
- Fixing mistakes in Custom CSS that require reinstallation
- Put settings into source control like github

**Comment by BreakBB** [comment]
According to [this comment](https://github.com/joelshepherd/tabliss/pull/281#issuecomment-702780450) on #281 the changes needed for this have been fixed with #292

**Comment by joelshepherd** [comment]
Implemented!

**Comment by mbierman** [comment]
Fabulous! Thank you.
