### ISSUE TITLE
Option to set time by +/-GMT

### ISSUE THREAD

**Issue by bakaoniisan** [joelshepherd/tabliss#26]
Could you have an option to set time by +/-GMT.

This would allow different time zones than the current system time.

There are times when I want to work by or keep track of other timezone. Also on firefox about:config?filter=privacy.resist.Fingerprinting changes the browser time from the system time (switches it to GMT).

**Comment by joelshepherd** [comment]
Hi, thanks for the suggestion. I have recently become aware of the resist fingerprinting config causing issues with timezones.

I think adding the option to manually set your timezone is an elegant solution, and provides extra customisation for people who would like to use it. Look out for this option in the next release!

**Comment by joelshepherd** [comment]
Added the option to manually set the timezone in the latest release `1.10.0`!
