### ISSUE TITLE
Allow link to local html files

### ISSUE THREAD

**Issue by h1777** [joelshepherd/tabliss#260]
Not all bookmarks are online. 
Would be cool to allow for `file://` links.

**Comment by True-cc** [comment]
Yes I agree. It doesn't work well. I have to open in new tab and reload the page; it''s annoying.

**Comment by lock-3** [comment]
> Yes I agree. It doesn't work well. I have to open in new tab and reload the page; it''s annoying.

Same here. A fix would be really nice!

**Comment by joelshepherd** [comment]
I don't believe browser's let extensions do this unfortunately :(
