### ISSUE TITLE
[Firefox Nightly] No focus on the address bar

### ISSUE THREAD

**Issue by nasskach** [joelshepherd/tabliss#264]
Hi,

When using Tabliss on Firefox Nightly no fucus on the address bar is done when opening a new tab or when having Tabliss as home page. 

I don't have this issue on Firefox stable. 

Any idea to fix that ?

SOME INFORMATION : 
Firefox Nightly 80.0a1 (2020-07-09) (64 bits)
macOS Catalina version 10.15.5

**Comment by GSquared** [comment]
I am also having this issue. When focusing manually on the address bar, sometimes text is cut off as well. Does not happen with extension disabled.

Info:
80.0a1 (2020-07-10) (64-bit)
Windows 10 x64 v2004

**Comment by NuclearCookie** [comment]
Same issue here.
Info:
80.0a1 (2020-07-13) (64-bit)
Window 10 x64 v1909

**Comment by averissimo** [comment]
This is definitely a problem with firefox and not isolated to tabliss

I was using momentum when I found this issue

**Comment by nasskach** [comment]
> This is definitely a problem with firefox and not isolated to tabliss

Yes, but does anyone know which change in Firefox is causing this behavior?

**Comment by averissimo** [comment]
One bug report on this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1652415

**Comment by averissimo** [comment]
Seems like it's fixed now in nightly _(as of an update this hour)_

And seems like this is the bugreport tracking it https://bugzilla.mozilla.org/show_bug.cgi?id=1596738

**Comment by nasskach** [comment]
Yes, this issue was fixed with the latest nightly release. I'm closing it. Thanks all !
