### ISSUE TITLE
[Suggestion] Search box tweak

### ISSUE THREAD

**Issue by brendanray** [joelshepherd/tabliss#27]
The distance between what you type (specifically the p's and q's of the alphabet) and the line you type it above seems too close. Perhaps adding a few pixels of padding would resolve the issue. Or thinning the line. Or both.

**Comment by joelshepherd** [comment]
Good point. I'll adjust the padding a touch in the next release.

**Comment by joelshepherd** [comment]
Fixed in the latest version `1.10.0` :)
