### ISSUE TITLE
More than 1 time zone

### ISSUE THREAD

**Issue by SuperGianchi** [joelshepherd/tabliss#271]
It'd be nice to have the possibility to display two or more time widgets with two or more different time zones.
For example, I'd like to have a new tab displaying

12:00
Rome
_ _ _
20:00
Sydney

In other words, each time widget should include its time zone.

Thank you,
Giancarlo

**Comment by gonzalrick** [comment]
Hi @SuperGianchi,

We merged a PR for this feature and will be included in the next release of Tabliss :)

Thank you
