### ISSUE TITLE
Obligatory "Is it dead?" issue

### ISSUE THREAD

**Issue by jlave-dev** [joelshepherd/tabliss#273]
Has @joelshepherd abandoned the project? Tabliss is a cool extension which I'd love to use. But with no commits since April and no one reviewing needed PRs, I'm not going to invest time configuring it if there won't be future improvements.

**Comment by gonzalrick** [comment]
Hi @jlave-dev, thank you for you interest in Tabliss! It is very much alive. We have been busy recently but we are trying to keep up with the pull requests and issues. 🙂

**Comment by jlave-dev** [comment]
> Hi @jlave-dev, thank you for you interest in Tabliss! It is very much alive. We have been busy recently but we are trying to keep up with the pull requests and issues. 🙂

Ok, good to know. Thanks!

**Comment by VersusF** [comment]
Hello, After 6 months since the last commit and 24 open pull requests the question is still there... Is the project abandoned? I use it daily and it has been great so far
