### ISSUE TITLE
Feature Request: Create Custom Widgets Widget

### ISSUE THREAD

**Issue by KelinciHutan** [joelshepherd/tabliss#274]
It'd be cool if we could, rather than making you do all the work, have a widget that allowed us to create custom widgets. To display scores from leagues other than the NBA, frex.

**Comment by trickypr** [comment]
This is an interesting idea and something I have been thinking about doing for ages. There are a number of options for doing this, all with their own pros and cons. I have tried to do something similar once with #177 for an issue that appears to be deleted. That implementation was imperfect and I would not recommend actually implementing it. Lets go through a few options that I can think up. 

1. Download / install some javascript from some trusted, signed source and execute it

In this method there would be some trusted install message similar to firefox addon store. This could provide a simple way of installing something for the user but would be a nightmare to secure. Firstly, we have experienced issues with csp trying to protect the addon from xss attacks with executing javascript in the addon. There is good reason for this, someone could write malicious code that takes advantage of the addons permissions (tabliss doesn't use any permissions so ¯\_(ツ)_/¯). 

There is also the issue of the additional hosting costs that could well fall on the repository owners. Hosting isn't free and something dynamic could cost with both development time and hosting.

You could also include third party scripts like #251.

2. Embedding iframes 

This method could solve a bunch of the security (& privacy) issues. It raises its own issues, like performance. Iframes add additional resource usage to a page, although it should be lazy loaded, so it will not affect overall page load time. 

This would be my preferred solution, with the query string (the `?[insert data here]` at the end of the url) being able to pass data down whilst still preserving user privacy. However, you have to deal with CORs and iframes, meaning you need to host it on a server that allows you to configure CORs (Github pages doesn't let you configure this, heroku free does).


This is quite large architecturally, meaning input from others is necessary. The project owners may not want something like this in the addon and they have the final say.

**Comment by luastoned** [comment]
What about pasting custom html/js code in an input field, much like custom css?

**Comment by trickypr** [comment]
Firefox (and maybe other browsers) has security protections to prevent a poorly coded webpage from being used maliciously. One of those protections is to stop custom JS from executing. We have run into this with #90 and #251. There is no way for us to disable it (probably a good thing considering the security implications).

**Comment by luastoned** [comment]
How are extensions like https://github.com/violentmonkey/violentmonkey working around it?

**Comment by trickypr** [comment]
Violent monkey (and other userscript managers) inject custom scripts into webpages using the [`tabs`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs) extension api. This api only works with non-addon websites.

As a browser addon, tabliss has access to special api's that can control the browser (and potentially to harvest data). To prevent malicious scripts from abusing these privileges, firefox prevents addons from executing dynamic code from within themselves.

**Comment by joelshepherd** [comment]
Yep @trickypr covered it pretty well. Custom js widgets will remain a web-only feature for the foreseeable future.
