### ISSUE TITLE
can no longer add more than 3 widgets to new tab page

### ISSUE THREAD

**Issue by GamerGirlandCo** [joelshepherd/tabliss#277]
today, my tabliss customizations just randomly reset, so i begrudgingly began to start rebuilding my homepage widget by widget

when i exited the settings panel and went to refresh the page to see if everything was looking okay, most of my widgets disappeared. so i tried to add them again, exited settings, and refreshed. again, every widget except the first 3 i added went away.

![image](https://user-images.githubusercontent.com/37163052/89449550-3ddfe080-d727-11ea-83c9-7c939b491d7c.png)
then....
![image](https://user-images.githubusercontent.com/37163052/89449612-53550a80-d727-11ea-88e7-9c39a4704cf3.png)

what gives..?

**Comment by trickypr** [comment]
I can't reproduce this at the moment, so could you provide me with some additional information?
- What browser are you using?
- If you right click, press inspect element, go to the console tab and try adding widgets, do you get any output in it? If so can you screen shot it.

**Comment by GamerGirlandCo** [comment]
hi again! sorry for the late reply ^^"

>     * What browser are you using?

* i'm using firefox

>     * If you right click, press inspect element, go to the console tab and try adding widgets, do you get any output in it? If so can you screen shot it.
* here's the message i get in the console:
![image](https://user-images.githubusercontent.com/37163052/90055068-c3750a80-dcaa-11ea-9bb0-3522cc6185fc.png)

**Comment by GamerGirlandCo** [comment]
i've managed to work out a temporary hacky fix:

1. go to your profile folder located in `%appdata%/roaming` -- i.e.;
`"C:\Users\<username>\AppData\Roaming\Mozilla\Firefox\Profiles\<profilename>"`
2. open up `storage-sync-v2.sqlite` in DB browser for sqlite. if you don't have this installed, get it [here](https://sqlitebrowser.org/dl/)
3. click on the "browse data" tab
4. in the "table" dropdown, select "storage_sync_data"
![image](https://user-images.githubusercontent.com/37163052/100553325-7a49c600-325b-11eb-81aa-3502f26ad718.png)
5. find the row that says `extension@tabliss.io` in the `ext_id` column
![image](https://user-images.githubusercontent.com/37163052/100553432-e62c2e80-325b-11eb-945c-b1416f7aed00.png)
6. change the `data` column value to an empty JSON object, i.e., `{}`
7. File -> Write Changes

saving your widgets should function normally now :)

**Comment by GamerGirlandCo** [comment]
update: i've figured out why this is happening - it's because firefox [imposed a new quota](https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/) for the `storage.sync` api. for context, i had added quite a bit of custom css, which must've taken up enough space that new additions/widgets could no longer be saved.
i mitigated this by uploading the custom css to my github pages site and replacing everything in that field with `@import url('https://gamergirlandco.github.io/custom.css')`. lo and behold, it works as it should, so i'll close this. sorry for wasting your time ^^"
