### ISSUE TITLE
[Suggestion] Add "Developer excuses" quotes

### ISSUE THREAD

**Issue by athityakumar** [joelshepherd/tabliss#28]
[The Developer excuses](https://addons.mozilla.org/en-US/firefox/addon/developer-excuses/) firefox add-on already has some good - you know - developer rant-like quotes in it. It'd be awesome to have these quotes show up with tabbie's awesome UI. 😄

**Comment by joelshepherd** [comment]
Ah those are hilarious (story of my life), I would love to integrate it! I can't seem to find any details of who runs the website though. I could just scrape the quotes, but I'd feel bad doing so without permission. I could link the quotes back to their website.

If anyone knows how I can get permission for developerexcuses.com, I would appreciate it!

**Comment by Smile4ever** [comment]
I e-mailed the person in charge of the website, we'll see.

**Comment by Smile4ever** [comment]
![image](https://user-images.githubusercontent.com/544411/36098735-5bda924c-1000-11e8-8c52-e472ffdc8560.png)
He agreed to let you use the quotes.

**Comment by joelshepherd** [comment]
Awesome, thanks! I'll work on it for the next update :)

**Comment by joelshepherd** [comment]
Developer excuses are now live :)

(In related news, I am still looking into the 'quote refresh on each new tab' to make quotes a bit more fun)
