### ISSUE TITLE
[Feature Request] Allow downloading of unsplash images

### ISSUE THREAD

**Issue by AlexandriaOL** [joelshepherd/tabliss#286]
I use Tabliss providing images from Unsplash, often I want to download the image as a desktop wallpaper. To do this, I have to middle-click on the unsplash button, wait for the page to load (Which can be frustrating in areas where the network is patchy), and then click on "download".

It would be nice if there was a dedicated button to do this.

**Comment by joelshepherd** [comment]
I have mentioned it elsewhere, but Unsplash have stated the prefer we do not add a download link directly into Tabliss. And since they give Tabliss a generous API usage quota, I respect that and won't be adding it sorry :(
