### ISSUE TITLE
[Feature Request] Add time zone for any city in Argentina

### ISSUE THREAD

**Issue by LongJohn-Silver** [joelshepherd/tabliss#290]
Title, basically, there's not a single Argentinian city to use as specified time zone.

**Comment by joelshepherd** [comment]
Sorry you are right!

I was missing pretty much every time zone that has 3 parts in them. Which every Argentinian city has (`Americas/Argentina/<City>`), and a few in the USA too.

A new list will be available in the next release!

**Comment by LongJohn-Silver** [comment]
Thanks a lot!
