### ISSUE TITLE
[feature requests] Hope to support config import and export or cloud sync

### ISSUE THREAD

**Issue by congjinyebaiya** [joelshepherd/tabliss#298]
Hope to add cloud service to sync config (such as  [infinitypro](https://addons.mozilla.org/en-US/firefox/addon/infinity-new-tab-pro-firefox/)). There is no way to sync tabliss config between two device or two browser now

Or maybe can support import and export feature to achieve it

![图片](https://user-images.githubusercontent.com/41639269/95651985-7681a900-0b20-11eb-848d-9a75d09da781.png)

**Comment by M0hammedImran** [comment]
Adding a button to export the current config and backup. Also, a way to edit it in a JSON file format.

**Comment by gonzalrick** [comment]
Hi @congjinyebaiya  and @M0hammedImran, this has been added to version 2.1.0 🙂
