### ISSUE TITLE
Suggestion: add high definition favicon

### ISSUE THREAD

**Issue by gabrielmulle** [joelshepherd/tabliss#3]
Hi man, 
I'd like to suggest, when you have time, to add a high definition favicon to Tabliss.
I only noticed it recently, in Mac retina display (because in my personal computer, with HD screen, it is hard to differentiate).
Thanks!
Gabriel

**Comment by joelshepherd** [comment]
Hi! I have changed the favicon to use a high resolution version of the full Tabliss logo. You should be able to see it in the next day or two when your extension updates :)

**Comment by gabrielmulle** [comment]
You're the best man.
