### ISSUE TITLE
Tabliss not syncing

### ISSUE THREAD

**Issue by SUPERSLEDZ666** [joelshepherd/tabliss#303]
Hi,  
Thanks for the great work I absolutely love the Tabliss. However I have small problem.  
I'm using Firefox 82 on my 3 computers with sync enabled for everything except passwords.
I've set up Tabliss on one and I was expecting that sync will push the changes to other 2 computers however it did not occur.

Is there anything I've done wrong? Can I somehow export settings and just manually import them?

**Comment by AliDjango** [comment]
same problem.tabliss doesnt sync on windows.but works on ubuntu 20.04
firefox 88 and 89 both have this problem

**Comment by joelshepherd** [comment]
Hello!

I'm not sure why it's not syncing your settings, but there are strict size requirements for synced data.

As for manually importing. You can import/export your settings at the bottom of the settings panel:
![image](https://user-images.githubusercontent.com/4484306/122521720-7eeb9580-d058-11eb-9ed3-65c03642a5cb.png)

Could you try exporting your settings and letting me know the size of the exported file?

**Comment by joelshepherd** [comment]
There isn't much I can go on here, so I'll close the issue for now.
