### ISSUE TITLE
Quick links issue

### ISSUE THREAD

**Issue by molitona** [joelshepherd/tabliss#317]
Hi, quick links are always opening in a new tab, how can I fix that ?

**Comment by JoaoAVDuarte** [comment]
For me it's opening correctly, check if you have browser settings changing the behavior from Tabliss.

**Comment by nazibalalam** [comment]
Just change it with the settings widget on top-left like this :- 
![image](https://user-images.githubusercontent.com/69672332/111485274-afbde500-8760-11eb-8b8c-ae92b292db41.png)
Just uncheck it if it's checked...
