### ISSUE TITLE
[Feature Request] Bug Fix   Need BLUR 

### ISSUE THREAD

**Issue by TreavVasu** [joelshepherd/tabliss#324]
### It's  bit Both: Feature and Bug  
From this, we clearly need a blur on the background or a different approach to handle this clearly it spoils the fun of the extension

Consider this 
![Screenshot from 2021-01-19 09-29-02](https://user-images.githubusercontent.com/16835617/104986317-cb469100-5a38-11eb-8c31-1ee0e07e6b29.png)

**Comment by CheriseCodes** [comment]
This feature already exists.

Background > Open Display Settings > Blur
