### ISSUE TITLE
Quick Link does not work to open local files

### ISSUE THREAD

**Issue by stevie-b-g** [joelshepherd/tabliss#337]
It would be useful when clicking a quick link, that points to a local file, i.e. file:///mydoc.pdf

it could open the located document.

Instead, I need to right click on the link and open it up in a new tab, and then refresh the page.

**Comment by ni3k** [comment]
It's a security issue, I had the same problem; chrome extensions can't access local files

**Comment by nazibalalam** [comment]
Is it on firefox or chrome?

**Comment by joelshepherd** [comment]
I have seen other extension doing some pretty elaborate hackery to get local links around the browser's built in security. That's not really the spirit of Tabliss so I won't be adding anything similar. But you might be able to use Tabliss in combination with those extensions to get it working? [Such an extension](https://chrome.google.com/webstore/detail/enable-local-file-links/nikfmfgobenbhmocjaaboihbeocackld?hl=en)
