### ISSUE TITLE
[Bug] Quote widget (position: top right) overlays and blocks icon for settings

### ISSUE THREAD

**Issue by VeraEngels** [joelshepherd/tabliss#339]
If you position the "Quotes" widget on the top right of the screen, it extends to the far left of the screen when the quote is very long. It then blocks the access to the settings cog-icon (as well as any other text positioned in the top left, for example quick links). 
Suggested solution: Limit the maximum width for widgets positioned at the right.

**Comment by joelshepherd** [comment]
The cog wheel now sits on top of all the widgets and is no longer blocked!
