### ISSUE TITLE
Long quotes break the UI

### ISSUE THREAD

**Issue by NotWearingPants** [joelshepherd/tabliss#340]
Usually:
![image](https://user-images.githubusercontent.com/26556598/107864965-ba881000-6e6a-11eb-96f0-54a74a18ecc9.png)

Rarely:
![image](https://user-images.githubusercontent.com/26556598/107864977-c8d62c00-6e6a-11eb-81c2-4eb20092f5c8.png)

Now I can't know what time it is 🤷‍♂️

I guess the same will happen if I just add a thousand links, but the height of quotes is random and unbounded, so there is no way to prevent this from happening.

I suggest a height limit to the quotes widget, and a scroll bar if it passes that height. (i.e. `max-width: 400px`). This is better than a scroll bar to the entire widget column, since consider what happens if the time widget is below the quotes - I want to guarantee the time widget will always be visible.

**Comment by CoderOO7** [comment]
> Usually:
> ![image](https://user-images.githubusercontent.com/26556598/107864965-ba881000-6e6a-11eb-96f0-54a74a18ecc9.png)
> 
> Rarely:
> ![image](https://user-images.githubusercontent.com/26556598/107864977-c8d62c00-6e6a-11eb-81c2-4eb20092f5c8.png)
> 
> Now I can't know what time it is man_shrugging
> 
> I guess the same will happen if I just add a thousand links, but the height of quotes is random and unbounded, so there is no way to prevent this from happening.
> 
> I suggest a height limit to the quotes widget, and a scroll bar if it passes that height. (i.e. `max-width: 400px`). This is better than a scroll bar to the entire widget column, since consider what happens if the time widget is below the quotes - I want to guarantee the time widget will always be visible.

Hi, I would like to work on this issue :)
