### ISSUE TITLE
[Feature] Option to hide image credits

### ISSUE THREAD

**Issue by mbledkowski** [joelshepherd/tabliss#344]
Hello,
Please add option to hide image's credits (left bottom corner).
Thanks ❤️

**Comment by nazibalalam** [comment]
That's the least you can do to appreciate unsplash, please deal with it.

**Comment by joelshepherd** [comment]
Unsplash gives Tabliss pretty generous API limits, so I won't be adding this as an option. But if you _really_ need to hide it, you can use the "Custom CSS" widget to do so.
