### ISSUE TITLE
[Request] Include Auto Address Bar Focus Setting

### ISSUE THREAD

**Issue by andym4321** [joelshepherd/tabliss#345]
When using Tabliss as a home page I would like to maintain the normal functionality of firefox home that focuses the address bar so I can just start typing in it immediately on launch. This behavior does happen in a "New Tab" scenario, but when initially launching firefox, using tabliss as the "Home Page", it does not auto focus the address bar.

**Comment by arielsboiardi** [comment]
I've been looking for a solution for some time now, and I still cannot figure out the problem... What system and version of firefox are you using? 

I am on Fedora 33 and using the version of Firefox from the main repository I have this problem. Yesterday I've tried to install the Flatpak version of Firefox and it would start with focus on the search bar.

**Comment by andym4321** [comment]
Im using plain, mainline Firefox and Windows 10. Currently Firefox version 86.0.1 64-bit and Windows version 2004. To be clear the auto focus functionality is only broken using tabliss as my home page specifically. Base Firefox auto focuses correctly and new tabs in an already open window focus correctly. It is just the first launch on startup of a brand new window that does not properly focus.

**Comment by arielsboiardi** [comment]
Yes, only when using tabliss (or any other webpage I suppose...).

I found some suggestions on how to focus ob the address bar with html tags which I tried to implement editing the page, but nothing worked for me. 
It migh also be firefox blocking this behaviour for some security reason.

**Comment by andym4321** [comment]
Well I appreciate the work you did on it. If it's firefox behavior then
there isn't much to do I suppose.

**Comment by joelshepherd** [comment]
In the latest version (2.2), Tabliss is now officially selectable as the homepage (as opposed to using a custom URL). From my testing, setting Tabliss to home using this method keeps the address bar focused!
