### ISSUE TITLE
Make tabliss take kyboard focus on new tab

### ISSUE THREAD

**Issue by nazibalalam** [joelshepherd/tabliss#353]
Hi, I've been using tabliss for a long time now and I've been recently contributing to it. So now my issue is, whenever I open a new tab it takes focus on the firefox link bar instead of the search bar in tabliss. Any suggestion would be helpful, thank you very much for your time.
![image](https://user-images.githubusercontent.com/69672332/111501204-f9153100-876e-11eb-9e29-ec378e0dfa86.png)

**Comment by joelshepherd** [comment]
I don't believe there is any way that an extension to control that. I believe firefox forces it to the URL bar. So I'll close this for now. If someone does know how to do it, I'm happy to look into adding it as an option.

**Comment by rui1121** [comment]
I've tried another firefox extension called [Mue](https://github.com/mue/mue), seems it always focus on firefox address bar whenever you opens a new tab.
