### ISSUE TITLE
[Bug] Homepage and new windows resets

### ISSUE THREAD

**Issue by tarikkavaz** [joelshepherd/tabliss#358]
I'm using Firefox 87.0 
I used to paste the `moz-extension://...` adress in my FF settings and tabliss was working on a new window as mentioned in the extenton settings. 
Now it doesn't.  On every restart of FF or a new window I get the default homepage. 
Side note: I'm syncying everything on FF with 4 different machines.

**Comment by augustusy** [comment]
I have the same problem, when restart PC and open chrome(89), the homepage reset to default, I have to import the backup json everytime, it seems the syn didn't work.

**Comment by tarikkavaz** [comment]
My guess is that the `moz-extension://****/index.html` file address changes with every computers browser. 
When it starts to sync it will get the file address from one of our other browser. 
It can't find one with the synced address so it goes back to the default homepage.

**Comment by joelshepherd** [comment]
Firefox has changed how it handled those extension addresses now, so the old solution no longer works. Luckily, Firefox has made the homepage settings more flexible now, so this will be fixed without a hack-around in the next version. See #182 for details.
