### ISSUE TITLE
Allow a font awesome icon to be set for quick links

### ISSUE THREAD

**Issue by brakenick** [joelshepherd/tabliss#36]
Allow a font awesome icon code eg. 'fa-shopping-cart' to be set in the optional Name field for the quick links widget and display the icon if one exists on the page.

![font-awesome-icons](https://user-images.githubusercontent.com/9064933/37565618-37890f32-2af8-11e8-9576-88f2f974c2fc.PNG)

**Comment by joelshepherd** [comment]
I notified this slightly to use the existing `feather-icons` icon set already in Tabliss. In the future I may add font awesome back when their v5 libraries stabilise a bit.

Other than that, icons are in!
