### ISSUE TITLE
[Bug] Tabliss as startpage not working in firefox 87.0

### ISSUE THREAD

**Issue by Staubgeborener** [joelshepherd/tabliss#368]
I am using Firefox 87.0.

In tabliss I go to settings, scroll all the way down and get my URL for the start page: moz-extension://randomid/index.html

Now I use this URL in Firefox as my homepage. Firefox itself does not show any errors. As soon as I close the settings window and click on the home icon (house symbol upper left corner), I land on the standard Firefox page. And indeed, when I go back to the settings it says "Firefox start page (default)". If I enter another URL, e.g. https://github.com/, it will be correctly adopted and saved. Has Firefox changed something in the conditions for start pages with regard to moz-extensions?

**Comment by Staubgeborener** [comment]
@nazibalalam Yep, the link is correct. Its working fine on my debian machine, but its not working as a startpage on my windows 10 system. But the problem should be somewhere in my configurations i guess

**Comment by NePoCz** [comment]
For those having the same issue, for me it was caused by "https everywhere". Solved by adding an exception for the tabliss url
