### ISSUE TITLE
It would be great if Tabliss could show Bible verses, like quotes.

### ISSUE THREAD

**Issue by BMatya** [joelshepherd/tabliss#369]
I like the quote option, something like that would be nice with verses from the Bible.

**Comment by kdkasad** [comment]
I think a better solution would be to allow for loading a custom list of quotes, so you can use whatever text you want.

**Comment by Staubgeborener** [comment]
Actually, most of the quotes are from this site: https://theysaidso.com/api/
And the API has random bible quotes: http://quotes.rest/bible/verse.json
Maybe I'll do a PR in the next few days.

**Comment by Staubgeborener** [comment]
@BMatya what is the correct quotation style for bible verse i.e. for this example?

```json
{
    "success": {
        "total": 1
    },
    "contents": {
        "verse": "The burden of the word of the LORD in the land of Hadrach, and Damascus shall be the rest thereof: when the eyes of man, as of all the tribes of Israel, shall be toward the LORD.",
        "number": "1",
        "chapter": "9",
        "book": "Hebrews",
        "testament": "New Testament",
        "bookid": "38",
        "uuid": null
    }
}
```

Should be something like `Hebrews 9:1` but honestly i don't have a clue.

**Comment by BMatya** [comment]
@Staubgeborener 
Yes, this is the correct format. Thanks.

**Comment by Staubgeborener** [comment]
@BMatya if you are still interested, my PR is now in the main branch: https://github.com/joelshepherd/tabliss/pull/370#event-5860537750

**Comment by joelshepherd** [comment]
Indeed, thanks for implementing
