### ISSUE TITLE
Allow to set different fonts for different widgets

### ISSUE THREAD

**Issue by gdelazzari** [joelshepherd/tabliss#37]
I'm not sure about a clean way (UI-wise) to implement this, but that 28px sized quote of the day under my 28px sized clock is hurting my eyes :(

The plugin is amazing, I really like it. But I really think this should be a feature. It could allow for bigger and smaller elements on the page, accomplishing a cleaner look.

Maybe instead of a global font setting (that is now located in the widget list, as a widget, which is a bit confusing) a little font/gear/settings icon could be placed on the right of each widget setting panel to allow for a custom setting for that specific widget.

I don't have a lot of time, but I may take a look at the code in the next weeks if this feature is interesting to you and I come up with a decent way of implementing it.

Anyway -and again-, thumbs up for the amazing project.

**Comment by joelshepherd** [comment]
Hi! I have the same thoughts about widget sizes too. I am currently considering/planning better ways of styling individual widgets, both in terms and size and position around the screen. I am also considering having a few "preset styles" of certain widgets that can contain different levels of information, similar to the current info toggle on the weather widget.

This is all a pretty big project and I haven't made much progress to it yet, but its something I want to work on over the coming months. It will probably be my target feature for "2.0.0".

Anyone is free to add their thoughts to the idea too.

**Comment by joelshepherd** [comment]
Circling back to this issue, this is indeed a target feature that has made it into 2.0.
