### ISSUE TITLE
[Request] Export/Import settings to a private gist

### ISSUE THREAD

**Issue by RVxLab** [joelshepherd/tabliss#377]
I think it would be amazing if you could export and import your settings to a private gist and keep them in sync using that.

I'd be willing to have a go at it to implement this.

**Comment by joelshepherd** [comment]
That's certainly cool, but using private gists involves storing access tokens, which requires me to update my privacy policy and data declarations. Possibly adding extra encryption too. I may tackle this in the future, but I am avoiding these kind of integrations for now. 

Fun fact though, Tabliss does save your setting to your browser's sync area? So if you're signed into Firefox Sync (for example), Tabliss will be synced for free.
