### ISSUE TITLE
Links should also open in new tab when using keyboard shortcut

### ISSUE THREAD

**Issue by cwils021** [joelshepherd/tabliss#380]
I think consistency would be great for Links opening in a new tab both when clicked or keyboard shortcuts are used when the option is selected, pretty sure the useEffect hook in Links.tsx just needs to be updated to use window.open instead of window.location.assign when option is selected

**Comment by cwils021** [comment]
PR #381

**Comment by joelshepherd** [comment]
Thanks for fixing it!
