### ISSUE TITLE
Unable to change Greetings[Bug] 

### ISSUE THREAD

**Issue by Ritesh-C07** [joelshepherd/tabliss#385]
By default greeting of Tabliss is Hello but I want to change it to greetings accordingly day time (like good morning, good evening, sleep well) but there is no customisation option for that on Firefox
   Bug is that it changed to this type of greeting (good morning, etc) it is not getting back to it

**Comment by joelshepherd** [comment]
Greetings are fixed per language. There is a bit of complexity involved with them, so I probably won't make them customisable.

Tabliss is open source though, so if you're handy with a bit of code, you could build a version with your own greeting strings.
