### ISSUE TITLE
Tabliss does not rotate every new tab

### ISSUE THREAD

**Issue by threkk** [joelshepherd/tabliss#39]
With the latest version of Firefox (59.0.1), opening a new tab does not change the background. On the previous version it was working. No action was made that would change the behavior.

Same behavior happens in the web version. In order to reproduce, go to the web version and open two tabs. The default image should be the same. No configuration was changed.

**Comment by joelshepherd** [comment]
Hi, it seems around this time I hit the Unsplash API limit for 5000 requests per hour, and no new images could be fetched. If Tabliss is properly rotating again now this looks to be the issue.

I'll send an email off to Unsplash support and see I can have Tabliss' API limit raised. Wish me luck!

**Comment by threkk** [comment]
Best of lucks! Tabliss is great and it really cheers up my day when I am in the office :)

**Comment by joelshepherd** [comment]
Good news everyone :) Unsplash has doubled Tabliss' API request limit to 10,000 request per hour. This should clear up the issue from happening for quite some time.
