### ISSUE TITLE
Allow users to access storage of Uploaded Images

### ISSUE THREAD

**Issue by joedachimp** [joelshepherd/tabliss#390]
I was looking to script updating my set of uploaded pictures. Instead of manually having to upload the set of photos from the tabliss settings interface, I think it could be very useful to update the set of files from the folder.
I did experiment with this and found that I don't know or understand enough about JavaScript and React. It appears the saved data gets entered into a SQLite DB, which becomes hard to alter from a python script.

**Comment by joelshepherd** [comment]
There is no easy way of doing this. Browsers are designed to make communication in/out of a pages secure sandbox as hard as possible.

This only way to communicate from the outside world into Tabliss (that I can think of) would be via [native messaging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging). But that's well outside the scope for what I plan to add to Tabliss myself sorry.
