### ISSUE TITLE
Link shortcut buttons

### ISSUE THREAD

**Issue by StijnHendriks24** [joelshepherd/tabliss#392]
Default Firefox customizable link buttons

**Comment by Gitoffthelawn** [comment]
What does this issue mean?

**Comment by StijnHendriks24** [comment]
I am talking about the option to add buttons similar to these.

Op di 23 nov. 2021 om 08:15 schreef Gitoffthelawn ***@***.***

**Comment by joelshepherd** [comment]
I am not sure if there was meant to be an attached image with this. But as it stands I don't really know what this is about.
