### ISSUE TITLE
[Feature request] Button to change background image

### ISSUE THREAD

**Issue by vdimir** [joelshepherd/tabliss#393]
Sometimes it's good to change background image not by time, but immediately (e.g. current image from Unsplash is too light or dark). So, it's nice to have button to reload image directly on page (e.g. near the settings button).

**Comment by Venryx** [comment]
I've found a workaround for this in the meantime.

Add the CSS below to a "Custom CSS" widget; it will add a pseudo-button to the top-left of the Settings panel, at the exact position that the settings button is at. The CSS styling repositions the radio button (of whatever background-image collection-type is *not* active) to that location.
```
.UnsplashSettings > label:nth-child(3) > input:not(:checked) {
    position: fixed;
    top: 15px;
    left: 18px;
    width: 20px;
    height: 20px;
}
.UnsplashSettings > label:nth-child(5) > input:not(:checked) {
    position: fixed;
    top: 15px;
    left: 18px;
    width: 20px;
    height: 20px;
}
```

This has the effect that:
* In that top-left rectangle, tap once to open settings.
* Tap a second time to switch to whichever is not active, of: "custom collection" and "custom search".
* Tap a third time to switch back to the previous collection-type.

Thus, triple-tapping in that top-left rectangle has the effect of refreshing the background image. (or double-tap, if you've set up both "custom collection" and "custom search" to give acceptable results)

And of course, if you don't like the image it gives, just keep tapping through the images that display.

**Comment by joelshepherd** [comment]
That was a very impressive CSS-based fix!

I have added a button in the next release to swap to a new image (or even go back to the last one!).

![image](https://user-images.githubusercontent.com/4484306/158832086-00bca870-7790-431f-8ed2-5765d581ad6d.png)
