### ISSUE TITLE
tabliss logs on the console of the developer tool at my firefox browser

### ISSUE THREAD

**Issue by jacobkim9881** [joelshepherd/tabliss#395]
Hello. Thanks for making such a nice extension. I have been used tabliss for over a year and nowadays I found some logs continuously created on my firefox developer console. And I found the extension id is for tabliss in my browser. The console logs screen's information at `main.js` at 16th line. And I don't know why these logs are created when I opened the developer tool on my firefox browser. Is there a way to fix it or stop the logs without deleting the extension?
![tabliss-console-log](https://user-images.githubusercontent.com/46774300/128482378-e3d381cb-5b1f-41b8-91b8-399d950cdcfe.png)

**Comment by joelshepherd** [comment]
Hi Jacob, that looks like something is logging events in your browsers.

I have no idea why though, there is nothing in Tabliss that logs to the console unless an error has occurred. Do you have any other extensions that might trigger some logs?

**Comment by jacobkim9881** [comment]
@joelshepherd Hi. I am not sure. I also have installed extensions and have developed extensions on chrome browser(it will not be the cause, I think). Currently, I opened tabs like 30 so I think it may be the cause.

**Comment by joelshepherd** [comment]
Does Tabliss still produce the logs if you close Firefox and reopen with just 1 tab?

**Comment by jacobkim9881** [comment]
@joelshepherd Yep, still logs. 

I am trying tabliss on Window 10 for now.

**Comment by jacobkim9881** [comment]
@joelshepherd When trying tabliss on Windows 10 without syncronizing a account or with syncronizing a account, there is no logs on console. Only on linux there are logs on console on my machine.

**Comment by jacobkim9881** [comment]
@joelshepherd Nevermind. Turns out all extension executed on `window` is logged on the console. Thanks, by the way!

**Comment by joelshepherd** [comment]
Ah awesome, glad you solved it. I was worried some malicious code worked its way into Tabliss for a second!
