### ISSUE TITLE
New search engine

### ISSUE THREAD

**Issue by azlux** [joelshepherd/tabliss#4]
Hi,
Can you use the default search engine of the browser ?
if not, it's can be good to add Duckduckgo, Qwant and Ecosia.

Thank !
Az

**Comment by joelshepherd** [comment]
Using the browser's default search engine was the original intention, but I haven't found a way to use it from within a web extension. I'm hoping they add an API to use the browser's search engine soon!

In the meantime, I have had a few requests for new search engines (DuckDuckGo in particular), so I'll be adding some more in the next release (hopefully tomorrow) :+1:

**Comment by joelshepherd** [comment]
New version just released with all said search engines :) You should see them in the next day or two when you're browser updates Tabliss.
