### ISSUE TITLE
Custom CSS For Advanced Users

### ISSUE THREAD

**Issue by defmonk0** [joelshepherd/tabliss#40]
It would be great if there was a location for advanced users to simply supply CSS to edit the view themselves.

There are a lot of small edits I would love to make, but they add up to a lot of dev time to add UI for very simple changes. It would be awesome if I could change them myself.

For example, a few edits I would make are:

- change the opacity on the Unsplash darken div to make it darker
- add a CSS blur filter to the background
- change the link style to remove underlines on hover
- change the links to inline-block so more could be on one line
- add drop-shadows to the text

They are all simple edits that are a matter of personal preference, and it would be great to be able to play with them.

**Comment by defmonk0** [comment]
If I started working on this, would you accept a PR? My idea is to supply a new widget with a textbox in the settings to paste the CSS, and then add a `style` tag to the UI with the css inside.

I've not used react in the past (I've been in more in the Angular camp), so if you can think of a significantly better way, let me know. From what I understand by looking at the source, the widget has two elements: a default one (for the UI), and a settings one (for the left-side settings bar). It seems pretty straightforward.

@joelshepherd

**Comment by joelshepherd** [comment]
Hi! I plan to do a few changes to the dashboard CSS in the future, however customisability does fit the mantra of what Tabliss is about, so I do support the idea. Mark it as Advanced/supply a warning message under the CSS box that states changes this is for advanced usage and the styles may update from time to time (or I could add something to that effect).

As for actual implementation, you are correct about the two components, one for dashboard that handles the actual widget logic, and one for settings that goes in the settings menu. Now I don't think there is a nice "React way" to inject user-definable CSS into the global scope, so you may need to settle for a dirty `document.createElement` hack to have it work.
