### ISSUE TITLE
Settings keep resetting

### ISSUE THREAD

**Issue by SystematicError** [joelshepherd/tabliss#404]
Whenever I open a new Firefox window, the tabliss extension keeps resetting. I unfortunately could not seem to reproduce it however I can include some info:

OS: Artix Linux
Firefox version: 91.0.2
Tabliss version: 2.1.0

**Comment by SystematicError** [comment]
It happened again today, I didn't update my system nor did I update tabliss

**Comment by augustusy** [comment]
#268

**Comment by Gitoffthelawn** [comment]
Would it be best to close this issue as a duplicate of #268?

**Comment by MJaroslav** [comment]
I have same problem on my two PC (win 10 and dual boot win 8.1/mint 20.2). Most often, a reset occurs during a reboot or OS change. Maybe it's because of the browser sync (I'm using the latest Chrome).

**Comment by Gitoffthelawn** [comment]
@MJaroslav See #268

**Comment by SystematicError** [comment]
> Would it be best to close this issue as a duplicate of #268?

Yea, this is a duplicate of https://github.com/joelshepherd/tabliss/issues/268, thanks for reminding me, this issue is going to be closed
