### ISSUE TITLE
Tabliss on latest stable Vivaldi 4.1.2369.21 (Stable channel) (64-bit) prevents website icons from loading and issues on startup.

### ISSUE THREAD

**Issue by CodeGrammer45** [joelshepherd/tabliss#406]
So on this release of Vivaldi, Tabliss will prevent website icons from loading effectively somehow. Sometimes the icons will load on the tab, but usually they will not. In either case, it takes a very long time for them to load.

Also, when Vivaldi first starts up, it will not open with Tabliss. It will only open with Tabliss if you open a new tab or go Home after starting up Vivaldi.

**Comment by joelshepherd** [comment]
This sounds like a Vivaldi bug sorry ☹️
