### ISSUE TITLE
[BUG] a weird bug in tabliss while using it with unsplash background remains unchanged

### ISSUE THREAD

**Issue by ramakrushna137** [joelshepherd/tabliss#414]
https://i.imgur.com/9iwnzog.png
https://i.imgur.com/vE3n8f2.png
https://i.imgur.com/VBDSMC9.png

so like the unsplash with random image from the unsplash was like first stuck on one photo and this it was complete black as the above photos and like doesn't change after every new tab so i hope you can fix it as fast as you can 
see ya and if there is a solution could you say it in a newb friendly way thanks

a Tabliss user

**Comment by joelshepherd** [comment]
I rewrote the Unsplash cache system in 2.4, hopefully that has solved the issue for you.
