### ISSUE TITLE
Feature Request: Custom Fonts

### ISSUE THREAD

**Issue by devangshekhawat** [joelshepherd/tabliss#416]

**Comment by SystematicError** [comment]
This is already possible, what widget are you trying to do this on? And what tabliss version?

**Comment by SystematicError** [comment]
You have to go to the font settings for the widget. If the widget for some reason does not have this option you can always just use custom css. For example, here is my clock widget using the Poppins font.
![image](https://user-images.githubusercontent.com/63366086/145236290-25d6da3b-7ce0-4ae6-bca6-15f762608a47.png)
