### ISSUE TITLE
Giphy integration does not work anymore

### ISSUE THREAD

**Issue by VonKavalier** [joelshepherd/tabliss#418]
When choosing a GIPHY background, the screen stays black, even on the [web version](https://web.tabliss.io/).

I'm guessing an expired authentification token.

**Comment by Jeshwin** [comment]
I am having the same problem as well.

Using Firefox 94 on my Macbook. I agree it may be an auth issue.

**Comment by diorcula** [comment]
In my instance it only displays the same Giphy, whether i change the search terms or not.

**Comment by vintprox** [comment]
I think we need something with API token option filled out by user: it's also more agreeable with ToS of GIPHY.

**Comment by juanmartinzzz** [comment]
just installed Tabliss and I'm experiencing the same issue. I'd be happy to provide my own API key somewhere but I don't see any way to do it. I'm on Firefox Developer Edition 97.0b4 (64-bit)

**Comment by vcbd** [comment]
Same problem. Resetting and reinstalling didn’t fix.
Error is `Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource` when Tabliss tries to fetch the actual gif, but getting the image url via Giphy’s random api point runs fine.

**Comment by stillnaenae** [comment]
also having this issue! I read that this user figured out how to set their own Api Key (https://giters.com/joelshepherd/tabliss/issues/366) but I dont know if it still will work, or if this is a different issue already fixed.

**Comment by w10000326** [comment]
> 

How did youusethe random api?

**Comment by stillnaenae** [comment]
I've been working on this here and there, researching what to do. I've gotten a good bit farther along, and have found that in the extension@tabliss.io .xpi file (Located at C:\Users\InsertNameHere\AppData\Roaming\Mozilla\Firefox\Profiles\ProfileNameHere\extensions) is the javascript file containing the api key that needs to be changed. For those also looking into this, you can access the contents of .xpi files as you would a .zip or .rar file, and extract them through something like 7zip or winrar. After going to the giphy developer website, registering as a developer and following their procedure to get an api key, I attempted to swap the key out with my new one. I opened the main.js file in notepad (I am a noob lol) and swapped the key for the new one. I believed i had it done after compressing the newly edited folder, only for firefox to say the extension was corrupted. I'm not sure on the protocol for packaging these xpi files so i consulted this:

https://stackoverflow.com/questions/19240653/how-to-create-xpi-file-with-7zip

Not sure where to go from here as I've just tried everything in the first couple of answers in the article.

**Comment by diorcula** [comment]
The sheer amount of people reacting and posting to this Github makes me wonder if the creator is still working on it, or is it just an abandoned project?

**Comment by w10000326** [comment]
From what I was reading, it seems an .env file needs to be created in order to actually use the API key. 

https://www.mariokandut.com/how-to-set-up-and-test-a-dot-env-file-in-node-js/

However, I am not as versed in Javascript.

**Comment by OneComputerGuy** [comment]
Ok so after a while of dragging Unsplash as my background and tried to change to Giphy and found this issue. Luckily, I have a bit of background with JavaScript/TypeScript and was able to track down the issue to a change in Giphy's response with the URL of the image.

I created a pull request adding the change, we'll have to wait until @joelshepherd reviews it and (hopefully) merges it.

https://github.com/joelshepherd/tabliss/pull/441

**Comment by w10000326** [comment]
just looked at the code. Nice job!!

**Comment by stillnaenae** [comment]
Wow thanks @OneComputerGuy !

**Comment by joelshepherd** [comment]
@OneComputerGuy's fix has been merged and will be release in the next week.

> The sheer amount of people reacting and posting to this Github makes me wonder if @joelshepherd is still working on it, or is it just an abandoned project?

Just time constraints unfortunately :(
