### ISSUE TITLE
Time is displayed incorrectly

### ISSUE THREAD

**Issue by aha999** [joelshepherd/tabliss#419]
Friend uses Microsoft Edge (sadly) on Microsoft Windows and installing Tabliss made him display the time incorrectly, as seen in his screenshot:

He was live streaming and time was shown 24:48 when it was in reality 0:48 in the morning.

![image](https://user-images.githubusercontent.com/50620416/142705992-b5d43b04-20e9-4846-b46d-6b42bc016b00.png)

**Comment by diksown** [comment]
I'm also having this problem on chrome, so I don't think it's a microsoft edge problem only.

**Comment by joelshepherd** [comment]
This should be solved now in version 2.2.0!

**Comment by joelshepherd** [comment]
I lied, it will be fixed in 2.2.1.
