### ISSUE TITLE
Tabliss saving 2 copies of every image

### ISSUE THREAD

**Issue by Gitoffthelawn** [joelshepherd/tabliss#421]
In the browser's local storage, Tabliss is temporarily saving 2 copies of every Unsplash image it downloads.

Tested with Tabliss v2.1.0 on Firefox 94.0.2.

**Comment by joelshepherd** [comment]
Tabliss is meant to fetch 2 Unsplash images when settings/etc change, under the `now` (current image) and `next` (next cached image) properties. When it hits the rotation timeout, it will move `next -> now` and fetch a new `next` image.

However it seems Unsplash's CDN now returns the same image for 2 calls to the "random" endpoint made close to each other (probably a caching optimisation). The side effect of this is the first 2 now/next images Tabliss loads when changing settings are the same.

It should fix itself when it rotates for the first time after a settings change, but I'll see if I can add some sort of timeout on the original load to fix the problem.

**Comment by Gitoffthelawn** [comment]
Thank you.  Sounds good.
