### ISSUE TITLE
Widgets-readability vs background -> add toggle for blur'ing background

### ISSUE THREAD

**Issue by yafp** [joelshepherd/tabliss#424]
I notced several times that the widget text is not always perfect readable - based on the background and it's colors.

What might be a perfect fix - at least from my point of view would be the following:

Let the user define blur for background - like he already can - this solves the readability quite good BUT reduces the advantage of a lovely wallpper.

How about adding a function to easily trigger the blur / unblur function for the wallpaper?

This would ensure we can see the wallpaper with its full beauty if needed - i.e. by double-click (as trigger for blur / unblur)

**Comment by noah-curran** [comment]
What about if the blur is removed when `toggleFocus()` is invoked? Meaning, either `w` is pressed or the eye icon is clicked. I imagine this is the only scenario where unbluring would be necessary in the use case you describe.

**Comment by noah-curran** [comment]
@yafp check out this branch: https://github.com/noah-curran/tabliss/tree/remove-blur-focue
Does this fit your needs? There are still some TODOS (i.e., considering whether to create a toggle for this, need to fix a bug that occurs when focus is enabled and page is reset), but it's mostly working.

**Comment by yafp** [comment]
@noah-curran 
there are no auto-generated builds right?
So i assume i have checkout ans build right?

Greetings

**Comment by noah-curran** [comment]
@yafp I'm not the owner of this repo, just contributing bc I'm bored and like this project. I don't think there is an auto build, but it's pretty easy to build yourself.
