### ISSUE TITLE
Tabliss breaks vivaldi://bookmarks/ in Vivaldi browser.

### ISSUE THREAD

**Issue by mikhasev** [joelshepherd/tabliss#425]
Subj. Can we get a fix, please? I really love this extension.
![image](https://user-images.githubusercontent.com/50861772/145604496-b3e25d4e-4d52-4e2e-95cc-38227b90ed0e.png)

**Comment by VegasKarma** [comment]
Same problem with vivaldi://history/

**Comment by joelshepherd** [comment]
Wow, never seen that before. I can't think of anything that would do that, possibly a Vivaldi bug?

Do you have any other info?

**Comment by joelshepherd** [comment]
From my research, this seems to be a bug in Vivaldi and there is no real workaround I can implement in Tabliss. https://forum.vivaldi.net/topic/69327/can-t-open-some-internal-pages-with-extensions-controlling-new-tabs/14

It sounds like the Vivaldi team are on it though.
