### ISSUE TITLE
Request: more languages

### ISSUE THREAD

**Issue by atirving** [joelshepherd/tabliss#426]
Hi Tabliss:  My students and I LOVE the beautiful photos when I open a new tab. Since I teach French, it was be amazing to have an option to switch Tabliss to French. Merci!

**Comment by joelshepherd** [comment]
You certainly can! To change the language of Tabliss, click the setting cog in the top right corner and selecting a new language from the dropdown at the bottom of the menu.

Do note that the settings menu hasn't been translated yet, but most widgets on the dashboard have been!

![image](https://user-images.githubusercontent.com/4484306/148664108-3c9f047f-b9a4-425c-b2f1-810b8ae40153.png)
