### ISSUE TITLE
"Display the Date" option in the Time widget displays the wrong month and day of week

### ISSUE THREAD

**Issue by tjb1019** [joelshepherd/tabliss#43]
First of all, thank you so much for you hard work!  Loving the extension.

I have noticed when enabling the "display the date" option for the time widget, the numerical date is correct, but the month and day of the week are incorrect.  Please see the screenshot below.

<img width="800" alt="date-ss" src="https://user-images.githubusercontent.com/8909680/38077635-7a922df6-32ee-11e8-9240-11aaa7707044.png">

**Comment by joelshepherd** [comment]
Hey! I noticed while using Tabliss today too. Turns out its a little quirk with how JavaScript handles month indexes. I have a fix ready and will be publishing it in the next few hours :+1:

**Comment by joelshepherd** [comment]
Fixed in version 1.11.2
