### ISSUE TITLE
Feature-Request: fullscreen at startup

### ISSUE THREAD

**Issue by Faetu** [joelshepherd/tabliss#432]
Hi,

would it be possible to add a option, which allows to make this addon starts at "fullscreen" (document fullscreen) ?

best regards

**Comment by joelshepherd** [comment]
Sorry, you can only activate fullscreen in response to a user interaction (such as a button click). [See note on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen).
