### ISSUE TITLE
[Feature request] Links to "about:" pages

### ISSUE THREAD

**Issue by sonofevil** [joelshepherd/tabliss#436]
I would like to add a link to my Tabliss layout that points to about:newtab, so I can quickly access frequently opened sites.

However, if I try to create a link for about:newtab, clicking it has no effect at all.

I'm not sure why it doesn't work, but if there is at all a way to make it work it would be nice.

**Comment by noah-curran** [comment]
What do you mean by no effect? `about:newtab` should just open a new tab, which would just open Tabliss again, as Tabliss is a new tab landing page extension. If your wish is to have frequently opened sites listed on the Tabliss page, then perhaps you're asking for a different feature altogether?

**Comment by noah-curran** [comment]
Looks like you're right (partially) -- my bad. First, I think you did misunderstand me on one part: I didn't meant to imply that about:newtab creates a new tab (bad wording on my part), but what you said about working in the current was what I meant. Sorry for the confusion about that. The rest you say about opening the default newtab is apparently true in the case of Firefox. For my case, I use Brave and about:newtab functions just as the UI or keyboard shortcut for newtab do (i.e., not in the same way as Firefox). This is where my confusion with your original post was related to re: "no effect".

I just did a dig, and I think I know why this doesn't work for you. See this code:
https://github.com/joelshepherd/tabliss/blob/main/src/plugins/widgets/links/Links.tsx#L16:L18
```js
data.linkOpenStyle
  ? window.open(data.links[index].url, "_blank")
  : window.location.assign(data.links[index].url);
```

If you were to input `about:newtab` to either `window.open()` or `window.location.assign()`, the behavior various from browser to browser. For Firefox, it will outright block it and gives `Access to 'about:newtab' from script denied.` in the console. For Brave, it blocks and opens `about:blank` instead. Regardless, it appears that what you want is not possible with how things are currently done, which explains why it doesn't work for you.

**Comment by joelshepherd** [comment]
Yeah the browser block direct links to `about:` pages most of the time. My guess would be to stop malicious websites from tricking people in changing their security setting in `about:config` or something. Either way, AFAIK there is nothing I could do to workaround this.
