### ISSUE TITLE
Feature Request - Strikethrough the done items in ToDo list

### ISSUE THREAD

**Issue by nair-sumesh** [joelshepherd/tabliss#438]
This feature will help reuse the the items again for future use.
Currently, user have to recreate the item (is a daily reoccurring item) every time the item is marked as done.

- Display the done items as strike-through
- Display the Radio button as checkbox
  - Empty/Unchecked = Not Done
  - Checked = Done

**Comment by joelshepherd** [comment]
Hi @nair-sumesh, if you turn on the checkbox circle at the bottom, it will show your complete todo items like so:

![image](https://user-images.githubusercontent.com/4484306/156869591-6c23751b-b1bb-4258-a78b-2aa15b319ee5.png)

I'll look into making the UI of todos a little more intuitive in the future.
