### ISSUE TITLE
Error creating new todo item

### ISSUE THREAD

**Issue by robeady** [joelshepherd/tabliss#447]
I just started seeing a very strange error as soon as I try to create a TODO item. Visually the item appears but on reload I find it has not been saved. 

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'stack')
    at Ue (main.js:16:72069)
    at G (main.js:16:81975)
    at y (main.js:16:75638)
```

I looked at the source code and can only assume this happens at https://github.com/joelshepherd/tabliss/blob/cb98a9664f2054632c4ba21f7f7f4059703ddf72/src/errorHandler.ts#L13 but how error can be undefined here I'm not sure

My best guess is that this is something to do with the number of visible todo items. It seems to happen or only happen when a vertical scroll bar appears in order to show them all?

I've attached my exported state/settings file with sensitive info scrubbed out (as txt because github doesn't support json attachments...)

[tabliss-scrubbed.json.txt](https://github.com/joelshepherd/tabliss/files/8152919/tabliss-scrubbed.json.txt)

Extra system info:
MacOS Monterey 12.2.1 (Intel)
Chrome 98.0.4758.109

**Comment by joelshepherd** [comment]
Hi @robeady, not sure why an `undefined` is being thrown there. It is a possibility you might be running up against the [maximum key size](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync#storage_quotas_for_sync_data) in your browser's sync storage?

If that's the case, deleting some of your old todos might fix the error for you. If that helps, the next version of Tabliss coming soon has a more efficient storage mechanism that should alleviate the problem for you.

**Comment by joelshepherd** [comment]
The next version of Tabliss was released with the more efficient storage and better error reporting. If you are still having issues, happy to reopen and investigate.

**Comment by robeady** [comment]
Thanks for letting me know. Yes, I think it's possible I was hitting the upper limit. I'll try out the new version :)
