### ISSUE TITLE
Dark Sky API Shutting down

### ISSUE THREAD

**Issue by DestroyerXyz** [joelshepherd/tabliss#451]
The Dark Sky API is shutting down by the end of this year (2022) as mentioned in #252.
[OpenWeatherMap](https://openweathermap.org/api) is the most popular and most recommended alternative.
Work needs to be started asap on using a new API or the weather function will stop working completely.

Thanks

**Comment by joelshepherd** [comment]
Hi @DestroyerXyz, thanks for the concern! Luckily, the shutdown was postponed till the end of 2022. Having said that, the work to replace DarkSky has already been complete and will be coming in the next release.
