### ISSUE TITLE
broken compatibility with old versions of Firefox

### ISSUE THREAD

**Issue by purple512** [joelshepherd/tabliss#454]
I'm using Waterfox Classic, which is a fork of Firefox 56 which allows using old style extensions.

On your addons.mozilla.org page, you list compatibility with Firefox 54, however Tabliss versions 2.2.1 and 2.3.0 are both broken. They die with a black screen and errors such as:

```
SyntaxError: expected expression, got '?'  main.js:2:340121
```

That corresponds to the expression:

```
timeZone:t.timeZone??null
```

Support for the nullish coalescing operator was added in Firefox 72, which means your stated compatibility with Firefox 54 is in error.

I have disabled automatic updates for Tabliss and I will keep using v2.1.0 which is the last working version. Either you need to mark your extension as requiring Fx 72 so that it won't try to update, or you need to not use this JS feature. I certainly hope for the latter but I understand that few authors are willing to go to the efforts required to support these very old versions of Firefox for the few users that use them. Thank you.

**Comment by joelshepherd** [comment]
Oh you're right, I hadn't thought about that. I've updated the minimum version of `2.2.1` and `2.3.0` to correctly state Firefox 72, so it should stop trying to auto-update now.

I've added a note to my pre-release checklist for the next version to see if transpiling away the operator is all that is needed to maintain 54+ compatibility (I may be I'm using other newer features too). If that works I'll release it as 54+ with the transpiling in place, if not I'll correctly update the minimum version going forward.

Sorry about that.

**Comment by joelshepherd** [comment]
Looks like transpiling worked! I will ship the next version with version 54 compatibility again.

![image](https://user-images.githubusercontent.com/4484306/159164550-48dc204c-c40e-4c78-9c41-f987b89d8178.png)

I can't promise to keep Firefox 54 compatibility, but I will try and be mindful and update the minimum Firefox version accordingly when that happens.

**Comment by purple512** [comment]
That's awesome, thank you very much!
