### ISSUE TITLE
[UX Improvement] Clarify that Widgets are Hidden

### ISSUE THREAD

**Issue by 0cwa** [joelshepherd/tabliss#458]
The .container div inside of the .fullscreen .Widgets div went completely empty out of the blue and the only thing that fixes it is resetting everything.  Even if I export and reimport my json or if I delete everything I've added, I still can't add anything in.  Here is a copy of my exported json after I've delete everything, you'll find you still can't add any widgets to it.  Tested on Firefox and Chrome:
```
{"background":{"id":"ea3fa8a8-2931-4ad0-86e5-481df95d3d39","key":"background/unsplash","active":true,"display":{"luminosity":-0.7,"blur":0}},"widget/default-time":null,"widget/default-greeting":null,"focus":true,"locale":"en","timeZone":null,"widget/gyuBYRW4459H":null,"widget/8c4f83e0-0e23-4e03-bd14-7d3aaf5dd87b":null,"widget/1a5921ba-2687-41e7-8b79-a006279bfa7d":null,"widget/8803346d-272b-4f9d-8c95-0cb72f7ea6fd":null,"widget/37d46e7c-be7a-4e87-bc05-5539fa54a13d":null,"widget/82c745d3-63db-4fe4-a08f-65dd9421643e":null,"widget/27797c92-a8b0-47ec-9e8b-c539ea670b51":null,"widget/febc4f06-8d5a-4d9b-ac8b-fb2cd3f7d60e":null,"widget/48e16c3c-18c2-466f-bea5-540b2bd63e31":null,"widget/0e019b4d-8ddb-44a3-8ffb-88683e6d957c":null,"widget/d13e9ff1-7fe3-4cd8-bba8-90f05300432a":null,"widget/1479f885-f5fb-4285-93e2-8aeed57c61c2":null,"widget/25ed3e22-a484-4530-926d-1140426e56df":null,"widget/d6dc2d91-c359-4f7c-a564-89067a99121e":null,"widget/6b101838-9855-4463-86e8-76d77df48dda":null,"widget/14e99b3a-f779-4650-bff8-8501c57c012f":null,"widget/a3fc11fe-21c9-4e9a-bc88-4b8d4eb6a161":null,"widget/a2f822f3-6fff-4fce-a455-143c9da30075":null,"data/ea3fa8a8-2931-4ad0-86e5-481df95d3d39":{"by":"search","collections":"","featured":false,"search":"","timeout":},"version":3}
```
I have a copy of my json before deleting everything (also broken), but I'd prefer to share it privately, thanks.

**Comment by joelshepherd** [comment]
Hi @0cwa, maybe you have the widgets turned off? This can only be triggered with the `W` shortcut.

<img width="183" alt="image" src="https://user-images.githubusercontent.com/4484306/159108720-d4a02944-26db-4c3e-ac81-c504b42d634f.png">

**Comment by joelshepherd** [comment]
This used to only be show/hide from the current tab, but now it saves your selection to the database. This change is because some users prefer to have widgets normally turned off, and only turn them on when they want to check something.

If this is indeed your issue, I might need to make the "widgets hidden" state more obvious.

**Comment by 0cwa** [comment]
That was it!  😅  I'd just turn the settings cog into the visibility button when widgets are hidden cause there's not really a point in editing anything when it's all invisible.  Thanks for the help!

**Comment by joelshepherd** [comment]
I've updated Tabliss to always show the "toggle widgets" button when widgets are hidden. Thanks for reporting
