### ISSUE TITLE
Bible Verse from They Said So has incorrect Book

### ISSUE THREAD

**Issue by agoldenlife** [joelshepherd/tabliss#462]
I switched to Bible Verses under the Quotes module and noticed that every day the book referenced is always incorrect.  The Chapter and verse are correct.

For instance today's
“And over against the border of the priests the Levites shall have five and twenty thousand in length, and ten thousand in breadth: all the length shall be five and twenty thousand, and the breadth ten thousand.”
— 1 Chronicles 48:13

However that is actually from Ezekiel 48:13.  Yesterday's said it was from Ezra but was actually from Ephesians.

Not sure if that is a problem with TheySaidSo, but wanted to bring it to your attention.  Thanks!

**Comment by joelshepherd** [comment]
Hi, it seems that is how it is being provided from They Said So.

You can try the call Tabliss makes: https://quotes.rest/bible/vod.json

```json
{
    "success": {
        "total": 1
    },
    "contents": {
        "verse": "And over against the border of the priests the Levites shall have five and twenty thousand in length, and ten thousand in breadth: all the length shall be five and twenty thousand, and the breadth ten thousand.",
        "number": "13",
        "chapter": "48",
        "book": "1 Chronicles",
        "testament": "Old Testament",
        "bookid": "26",
        "uuid": null
    }
}
```

You could try contacting They Said So and seeing if they can find out what's going on.
