### ISSUE TITLE
Extension died after I switched the language from Russian to Portuguese

### ISSUE THREAD

**Issue by 1280px** [joelshepherd/tabliss#463]
So I switched the language of my Tabliss to Portuguese and now it... it just doesn't work anymore.
![изображение](https://user-images.githubusercontent.com/71165491/160069783-85a45e32-cb27-4c0e-a933-295c9c592949.png)

It only shows me the black screen, and the page itself lacks any control elements:
![изображение](https://user-images.githubusercontent.com/71165491/160069071-a662c616-ba6d-4414-85c8-ed7d770926a9.png)
(the console is empty too, no any errors or log messages)

I tried to re-install the extension but it somehow preserves the data from deletion and still shows me completely empty black page. Firefox 99.0b6

**Comment by TheOnlyGhostwolf** [comment]
Hello! I'm having the same issue, but without changing any settings. Seems like the recent update is to be blamed.
![image](https://user-images.githubusercontent.com/31188082/160074710-82e44cee-87b8-4d25-90d5-c25efd98b8e7.png)

Using Firefox 98.0.2

**Comment by joelshepherd** [comment]
Hi guys, yes the recently update (2.4.0) is to blame.

I noticed the bug almost immediately, but the fix (2.4.1) has been stuck in the Firefox Addon's review queue for over 16 hours(!) so far :( I am really hoping they approve it soon.

**Comment by TheOnlyGhostwolf** [comment]
Got it! Thanks for your response.

**Comment by joelshepherd** [comment]
The fix has been approved and released! There was an additional bug with the language switcher that has also been fixed with a subsequent release (2.4.2).
