### ISSUE TITLE
Feature Request - NASA Image of the Day

### ISSUE THREAD

**Issue by diorcula** [joelshepherd/tabliss#467]
It would be cool to have the option to display NASA's image of the Day;
NASA has an open API for such things, but as I'm not able to work this out for the time being I thought I should just share my idea with all of you.

I hope this summer I will have some spare time to take this upon me, but if anyone feels like doing it I'd say go for it :P

Let me know what you think.

Love,

Diorcula

**Comment by joelshepherd** [comment]
Astronomy picture of the day looks good: https://api.nasa.gov/

**Comment by joelshepherd** [comment]
After further investigation, I can't seem to find a suitable source of high quality images. Astronomy of the day seems to contain lots of small(er) image sizes and not great backgrounds.

**Comment by diorcula** [comment]
i will try to find a good source; else i will close the request/feature!

**Comment by diorcula** [comment]
Nasa indeed did not have high quality images available, the Picture of the Day often is not of sufficient quality; although it is still fun if you don't care about quality.
