### ISSUE TITLE
Feature Request - Load Custom CSS sooner

### ISSUE THREAD

**Issue by yokai64** [joelshepherd/tabliss#468]
Hi, me again!

I know Custom CSS is technically unsupported and only for advanced users, but I noticed that occasionally there's a bit of a jump before it gets loaded it. It's not a big deal, but it would definitely improve the UX.

Here's a video of what I mean **(Video is a little flashy with images popping in and out)**:
https://user-images.githubusercontent.com/20884861/160706713-d408be12-4795-42d9-a4ae-38776478f9d0.mp4

As you can see, the links, date and greeting briefly show in their default position before the CSS loads. It's not a bit deal, like I said, but if it didn't have that issue that would really improve the UX imo

**Comment by yokai64** [comment]
Quick note: this is more easily reproduced using Hard Reload (CTRL + Shift + R)

**Comment by joelshepherd** [comment]
Got you covered.
