### ISSUE TITLE
Only background on 2.4.2

### ISSUE THREAD

**Issue by linsui** [joelshepherd/tabliss#469]
![图片](https://user-images.githubusercontent.com/36977733/160735099-97ab1e52-e573-48fc-9b56-6bed24300ca8.png)

The widgets disappeared suddenly. I'm on Firefox. Could you please take a look? Thanks!

**Comment by joelshepherd** [comment]
Hi @linsui, widgets can be toggled on or off with the eye icon next to the settings cog.

This icon:
![image](https://user-images.githubusercontent.com/4484306/160757662-f47d068f-9a94-4e8b-b892-3958bee10406.png)

**Comment by linsui** [comment]
Wow, thanks!
