### ISSUE TITLE
FeatureReq: Tweet the daily quote

### ISSUE THREAD

**Issue by nisrulz** [joelshepherd/tabliss#47]
It would be really nice to be able to tweet the daily quote that shows up, by having a simple small twitter icon right next to it.

Note: I can help in development, I am just not sure about the web side of things. I do have a tweet api setup in my readme as [here](https://github.com/nisrulz/sensey) and in other projects.
It is a simple link which you feed Encoded text
```
 <!- Check the href part-->
<a href="https://twitter.com/intent/tweet?text=Sensey%3A%20Android%20library%20which%20makes%20playing%20with%20sensor%20events%20%26%20detecting%20gestures%20a%20breeze%F0%9F%98%8E&url=https://github.com/nisrulz/sensey&via=nisrulz&hashtags=AndroidDev">
        
        <!- this is the badge image -->
        <img src="https://img.shields.io/twitter/url/http/shields.io.svg?style=social"/>
    </a>
```
The final link shows up like [this](https://twitter.com/intent/tweet?text=Sensey%3A%20Android%20library%20which%20makes%20playing%20with%20sensor%20events%20%26%20detecting%20gestures%20a%20breeze%F0%9F%98%8E&url=https://github.com/nisrulz/sensey&via=nisrulz&hashtags=AndroidDev) 

Here is how the link is broken down
1. `<a href="https://twitter.com/intent/tweet?text=`
     > The tweet intent
1.  `Sensey%3A%20Android%20library%20which%20makes%20playing%20with%20sensor%20events%20%26%20detecting%20gestures%20a%20breeze%F0%9F%98%8E` 
     > Url encoded text, use [this tool to decode and encode](https://meyerweb.com/eric/tools/dencoder/)
1. `&url=https://github.com/nisrulz/sensey`
    > Url to include
1. `&via=nisrulz`
    > Add via text
1. `&hashtags=AndroidDev"`
    > add a hashtag

Let me know if you would need any help

**Comment by joelshepherd** [comment]
I have decided to keep Tabliss free from social media integrations - sorry!
