### ISSUE TITLE
Safari web version loses settings

### ISSUE THREAD

**Issue by mbierman** [joelshepherd/tabliss#472]
As covered in https://github.com/joelshepherd/tabliss/issues/268, Safari randomly loses customizations. I have to re-import settings.

**Comment by joelshepherd** [comment]
Could you post extra details in #459?

Additionally, in version 2.5 I have added an option that will request the browser store Tabliss's settings in permanent storage. Support in Safari is very new, so the option may not come up for you if you are using a slightly older version.
![image](https://user-images.githubusercontent.com/4484306/161378617-5c554e37-3e30-4fc4-a0d3-f7df50ce2e61.png)
