### ISSUE TITLE
black screen on brave browsee

### ISSUE THREAD

**Issue by VenomFate-619** [joelshepherd/tabliss#474]
![image](https://user-images.githubusercontent.com/67755128/161879321-8fbf108f-2768-49fc-b780-d94a23266bcb.png)

Brave version :- 1.37.109 Chromium: 100.0.4896.60 (Official Build) (64-bit)
OS :- PopOs
Tabliss version :- 2.5.1

**Comment by joelshepherd** [comment]
Hi! Are there any errors printed in the console?

**Comment by VenomFate-619** [comment]
No, 😅 there is not a single error message

**Comment by joelshepherd** [comment]
Oh excellent :D

Does Brave have the ability to create a new profile like Chrome does? https://support.google.com/chrome/answer/2364824
If so, could you try installing Tabliss on a new profile and seeing if it works there?

**Comment by VenomFate-619** [comment]
it gets resolved automatically as I restart my browser.
Thx for your time.

**Comment by joelshepherd** [comment]
Oh? I have had reports of that happen on Firefox, especially after a Tabliss update. But good to know to watch out for that on Brave too.
