### ISSUE TITLE
Feature request: widget to insert HTML (safe) or JS (more scary) content form response on HTTP-call ?

### ISSUE THREAD

**Issue by Madydri** [joelshepherd/tabliss#476]
If this could be possible, it could open possibilities in pro application field
Some indicators or content could be live called and inserted in the new tab page
Do not know if an extension can get authorization to do this ?
I suppose it is doable as there is already a "NBA Scores" widget : so the data must be get outside the browser and/or local host.

**Comment by joelshepherd** [comment]
Hi, the Chrome and Firefox extension policies prohibit loading arbitrary JS from outside the extension:

> Add-ons must be self-contained and not load remote code for execution.

The NBA plugin works by _only_ pulling in data with a HTTP call. The JS and HTML used to display the NBA widget is contained [within the extension](https://github.com/joelshepherd/tabliss/tree/main/src/plugins/widgets/nba). This policy however, does not exist for the [web version](https://web.tabliss.io/). If you use the web version, you can use the "Custom JS" widget to add your own JS to Tabliss already!

As for only pulling in HTML, I am not entirely sure if it is permitted or not. But considering the Firefox addon linter flags any function that adds HTML to the DOM directly, I am going guess its a no. Sorry, but this feature can only live in the web version.
