### ISSUE TITLE
Add Tabliss to the Microsoft Edge Store

### ISSUE THREAD

**Issue by NashJames** [joelshepherd/tabliss#478]
https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home

I imagine it's not obvious to everyone you can use Chrome Store Add-ons on Edge. Plus, you have to go through this "Be careful of dangerous third-party stores" thing to add one on Chrome.

**Comment by joelshepherd** [comment]
Yeah, I have been meaning to do this for a while now. Soon, I promise :joy:

**Comment by joelshepherd** [comment]
Brand new to the Edge store :)
https://microsoftedge.microsoft.com/addons/detail/lklaendlmlfkaabeleddanafeinnenih
