### ISSUE TITLE
[Feature Request] Add fallback for "gogeoip.com" to IP Info widget

### ISSUE THREAD

**Issue by Hubza** [joelshepherd/tabliss#482]
For the last few hours or possibly days, https://www.gogeoip.com/ has been down and returning a 503, which has left the IP status on my new tab page to be an IP which i no longer am under (since i use Dynamic IP) - I think adding fallbacks in case gogeoip.com is down would be a good idea?

I'm not sure when it(gogeoip) went down, but probably in the last 2 days, since I last restarted my router two days ago (which is what causes the ip change)

**Comment by joelshepherd** [comment]
I would be keen to add a fallback. Do you know of a reliable geoip services?

**Comment by Hubza** [comment]
afraid i don't know of any off the top of my head, but after looking into it a little bit:
- http://ip-api.com/json/ is completely free, and though more for location also returns your ip
- https://ipwho.is/ similar to the last one, still more for location but has the ip
hope that helps

**Comment by joelshepherd** [comment]
Thanks for finding those! A fix coming in the next release :)
