### ISSUE TITLE
How do I remove this extension info in Firefox address bar?

### ISSUE THREAD

**Issue by Taughtimp2786** [joelshepherd/tabliss#525]
I want to remove the ` Extension (Tabliss)`:
![Screenshot (4)](https://user-images.githubusercontent.com/77712873/183973715-2d9c1cca-7589-418b-973c-0208e17f50dc.png)
from my address bar because it just takes up unnecessary space

**Comment by Taughtimp2786** [comment]
How do I remove it?

**Comment by vovavili** [comment]
Add this to your userChrome.css:

```
/* Tabliss CSS */

#identity-box.extensionPage #identity-icon-label {
    display: none !important;
	background: none !important;
}
#identity-icon-box {
    background: none !important;
}


```

**Comment by Taughtimp2786** [comment]
Thanks. It worked and I don't see it anymore:
![Screenshot (23)](https://user-images.githubusercontent.com/77712873/185944667-1ed43515-07c1-42b5-8fbb-4f1df3b1bc8e.png)
