### ISSUE TITLE
Hide ( this page is loaded by extension)

### ISSUE THREAD

**Issue by PhoenixCODE2322** [joelshepherd/tabliss#536]
![image](https://user-images.githubusercontent.com/75798544/194721656-02bc778f-25e3-4aca-9390-72e8870eb03c.png)

How do i hide it , i am already using userChrome.css files, if i can get the code to hide it. Or is there another way ?

**Comment by priyavrat-misra** [comment]
[This](https://github.com/datguypiko/Firefox-Mod-Blur) might help, I suppose.
