### ISSUE TITLE
[Issue] Cursor does not go to URL field upon new tab on Mac OS X

### ISSUE THREAD

**Issue by nocode99** [joelshepherd/tabliss#54]
On my Linux box - when I open a new tab with tabliss, it will automatically put my cursor in the URL field so I can immediately start typing in an address or search.

On Mac OS X - this isn't automatic and I have to hit  ⌘+L to get my cursor to the URL field.

I'm on High Sierra and using FF 59.0.2.

**Comment by joelshepherd** [comment]
Hey, does this seem to be the issue you're having? https://github.com/joelshepherd/tabliss/issues/25

**Comment by nocode99** [comment]
Ah yes it is.  I read the issues but I didn't know what Awesomebar was referring to.  Thanks!
