### ISSUE TITLE
Rotating among custom images

### ISSUE THREAD

**Issue by MrJJJ** [joelshepherd/tabliss#6]
Amazing alternative to momentum, thanks! Would be really cool to allow to upload a bunch of custom wallpapers.

**Comment by joelshepherd** [comment]
Hi! For a status update: I'm currently investigating better ways to store lots of photos/wallpaper in the settings storage in the browser. During my testing, storing more than a 2-3 images in the settings store starting to really affect load time on Tabliss (how quickly Tabliss shows after you open a new tab).

I really want to implement this feature, so now that I've finished the Quick Links widget, this will be my next mission to solve :)

**Comment by joelshepherd** [comment]
It took a little bit of experimenting.. and you'll need to select your image again.. but the 'Upload Images' background now accepts multiple uploads and it is working smoother than ever!

Thanks for your patience for this one. You should see the update in the next day or two when your browser updates Tabliss :)

**Comment by MrJJJ** [comment]
Nice, that's great, many thanks!
