### ISSUE TITLE
[Suggestion] Hide Tabliss Icons when it is not hovered by the mouse pointer.

### ISSUE THREAD

**Issue by AldegarDespoina** [joelshepherd/tabliss#60]
Is it possible to add such feature in the options section?

**Comment by joelshepherd** [comment]
Do you mean the icons in the top left corner of the view?

**Comment by AldegarDespoina** [comment]
Yes.

**Comment by joelshepherd** [comment]
I'll look to add this feature once I add a "first-run tour" to Tabliss. This is because some new users already have a hard time finding how to edit the settings!

**Comment by joelshepherd** [comment]
![image](https://user-images.githubusercontent.com/4484306/62600510-6c6b8580-b932-11e9-9de7-02533f1ab239.png)
The corner icons (except the settings cog) will now hide until hovered in the next version.
