### ISSUE TITLE
Russian language & other features

### ISSUE THREAD

**Issue by kristall000** [joelshepherd/tabliss#62]
Hello! I really like your add-on, it's very beautiful and awesome! But I didn't find in it my native Russian language. I could help to translate the extension, or at least it would be nice to be able to manually enter certain lines.

The second problem concerns search engines. I would very much like to see the search engine [Yandex.ru](https://yandex.ru) and [Mail.ru](https://mail.ru/). In the same way it should be nice to have the ability to set custom search engine, it can be very useful for many people. For example, define a certain field of the domain and the question itself:
_`https://yandex.ru/search/?text=%question%`_

Thank you, I look forward to your reply.

**Comment by joelshepherd** [comment]
Hi, I'm glad your enjoying Tabliss!

I have added those search engines for you! They will be available in the next Tabliss release. Custom search engines is not a feature I'm planning to develop myself in the near future.

For Russian translations, I can't add that feature myself 🙁 Someone has started a Pull Request to add the translations, but didn't finish: #61. If you would like to help here, feel free to create a Pull Request with Russian translations and I will merge them in. If you would like an example, the German translation is a good reference for what you need to add: #41.

Hopefully we can have the Russian translations + search engines is Tabliss shortly!

**Comment by kristall000** [comment]
I'm currently working on a translation.. but
If select background type GIPHY, there will be a typo in "sCretch to fill screen". "sTretch" will be correct, or not?

**Comment by kristall000** [comment]
Oh.. I was hoping that it's possible to translate all the lines. Unfortunately I did not see your message on time. In any case, here is 95% of the translation of everything that exists.

**_\tabliss-master\src\app\settings\Settings.tsx_**
Background = Фоновое изображение
Widgets = Виджеты
Reset to default = Значения по умолчанию

**_\tabliss-master\src\app\settings\Background.tsx_**
Background = Фоновое изображение

**_\tabliss-master\src\app\settings\Widgets.tsx_**
Widgets = Виджеты
No widgets selected = Нет выбранных виджетов
Add a new widget = Добавить новый виджет

**_\tabliss-master\src\plugins\backgrounds\register.ts_**
Solid Colour = Сплошной цвет
Colour Gradient = Градиент
Upload Images = Локальные изображения

**_\tabliss-master\src\plugins\backgrounds\colour\ColourSettings.tsx_**
Colour = Цвет

**_\tabliss-master\src\plugins\backgrounds\dribbble\DribbbleSettings.tsx_**
Normal quality = Нормальное качество
I hate my CPU quality = Я ненавижу свой CPU

**_\tabliss-master\src\plugins\backgrounds\giphy\GiphySettings.tsx_**
Tag = Метка
Allow NSFW = Разрешить NSFW
Scretch to fill screen = Подогнать изображение

**_\tabliss-master\src\plugins\backgrounds\gradient\GradientSettings.tsx_**
From Colour = Первый цвет
To Colour = Второй цвет
Angle (0-360) = Угол (0-360)

**_\tabliss-master\src\plugins\backgrounds\unsplash\UnsplashSettings.tsx_**
Show a new photo = Как часто сменять изображение:
Every new tab = Каждую новую вкладку
Every 15 minutes = Каждые 15 минут
Every hour = Каждый час
Every day = Каждый день
Pause = Пауза
Official collection = Официальная подборка
Custom collection = Выбрать подборку
Collection ID number = Укажите ID подборки
Custom search = Индивидуальный поиск
Tags = Метки
Try landscapes or animals... = "Животные" или "Animals" и т.д.
Only featured images = Только избранные изображения
Slightly darken = Затемнение

**_\tabliss-master\src\plugins\widgets\register.ts_**
Custom CSS = Пользовательский CSS
Font Settings = Настройки шрифта
Greeting = Приветствие
Quick Links = Ссылки
Message = Строка
Daily Quotes = Цитаты
Search Box = Поисковая строка
Time = Часы
Todos = Список дел
Weather = Погода

**_\tabliss-master\src\plugins\widgets\font\FontSettings.tsx_**
Family = Название шрифта
Size = Размер
Weight override = Толщина
Color = Цвет

**_\tabliss-master\src\plugins\widgets\time\TimeSettings.tsx_**
Analogue = Аналоговые
12-hour digital = Цифровые (12 часов)
24-hour digital = Цифровые (24 часа)
Display the date = Показывать дату
Monday = Понедельник
Tuesday = Вторник
Wednesday = Среда
Thursday = Четверг
Friday = Пятница
Saturday = Суббота
Sunday = Воскресенье
January = Январь
February = Февраль
March = Март
April = Апрель
May = Май
June = Июнь
July = Июль
August = Август
September = Сентябрь
October = Октябрь
November = Ноябрь
December = Декабрь
**Date format**: %Month% %DayOfMonth%, %WeekDay%
otherwise there will be language errors or you will have to add a lot of exceptions. I think this formatting could be the easiest way.

**_\tabliss-master\src\plugins\widgets\css\CssSettings.tsx_**
CSS Snippet = Фрагмент CSS
Warning: this functionality is intended for advanced users. Custom styles may break at any time. = Предупреждение: эта функция предназначена для продвинутых пользователей.	

**_\tabliss-master\src\plugins\widgets\greeting\GreetingSettings.tsx_**
Name = Имя:

**_\tabliss-master\src\plugins\widgets\greeting\messages.ts_**
greetings:
0 = Приятных снов
1 = Пора спать
2 = Добро пожаловать в ночную смену
3= Доброй ночи
4 = Доброй ночи
5 = Проснись и пой!
6 = Доброе утро!
7 = Проснись и пой!
8= Доброе утро!
9 = Привет!
10 = Добрый день!
11 = Привет!
12 = Добро пожаловать!
13 = Здравствуйте!
14 = Добрый день!
15 = Добро пожаловать!
16 = Привет!
17 = Добрый день!
18 = Добро пожаловать!
19 = Добрый вечер
20 = Здравствуйте!
21 = Добрый вечер
22 = Доброй ночи
23 = Спокойной ночи
with name:
0 = Приятных снов, {name}
1 = Пора спать, {name}
2 = Добро пожаловать в ночную смену, {name}
3 = Доброй ночи, {name}
4 = Доброй ночи, {name}
5 = Проснись и пой, {name}!
6 = Доброе утро, {name}!
7 = Проснись и пой, {name}!
8= Доброе утро, {name}!
9 = Привет, {name}!
10 = Добрый день, {name}!
11 = Привет, {name}!
12 = Добро пожаловать, {name}!
13 = Здравствуйте, {name}!
14 = Добрый день, {name}!
15 = Добро пожаловать, {name}!
16 = Привет, {name}!
17 = Добрый день, {name}!
18 = Добро пожаловать, {name}!
19 = Добрый вечер, {name}
20 = Здравствуйте, {name}!
21 = Добрый вечер, {name}
22 = Доброй ночи, {name}
23 = Спокойной ночи, {name}

**_\tabliss-master\src\plugins\widgets\message\MessageSettings.tsx_**
Message = Текст:

**_\tabliss-master\src\plugins\widgets\search\Search.tsx_**
placeholder - plugins.search.placeholder
defaultMessage = Введите запрос
description = Текст, который будет отображаться в окне поиска, прежде чем будет введён запрос

**_\tabliss-master\src\plugins\widgets\search\SearchSettings.tsx_**
Placeholder = Фоновый текст
Type to search = Введите запрос
Provider = Поисковая система

**_\tabliss-master\src\app\settings\Feedback.tsx_**
Send feedback or suggestions = Отправить отзыв или предложение
Your email (optional) = Ваш email
Your feedback or suggestion = Ваш отзыв или предложение
Close feedback form = Закрыть форму обратной связи
Feedback API request was not successful = Отправка отзыва обратной связи не удалась
Thank you for your feedback = Спасибо за ваш отзыв
Sorry, we were unable to send your feedback :( Please email your feedback to feedback@tabliss instead. = Извините, мы не смогли отправить ваш отзыв :( Пожалуйста, отправьте ваше письмо на feedback@tabliss

**Comment by joelshepherd** [comment]
Thank you for this! All the others will come in handy when I get the settings menu ready to be translatable. For now, I have added all your translations in for the current dashboard. You can test them at the beta url: https://tabliss-beta.s3.amazonaws.com/index.html

There were 2 missing translations (Quick Links widget hover text) but they are relatively minor and I am happy to push through without them.

If you can however, translations for both `defaultMessage`s would complete the current dashboard!
```
  {
    "id": "plugins.links.shortcutHint",
    "description": "Hover hint text for links with a keyboard shortcut",
    "defaultMessage": "Press {number} or click to visit"
  },
  {
    "id": "plugins.links.standardHint",
    "description": "Hover hint text for links without a keyboard shortcut",
    "defaultMessage": "Click to visit"
  },
```

Last note is I think a few of the greetings translation were out of order? For example, "good afternoon" at 10am. I tried to fix the order of ones that looked out of place, but you might want to check them over and make sure I didn't make mistakes. You can see what I came up with here: https://github.com/joelshepherd/tabliss/blob/master/src/locales/lang/ru.json

**Comment by kristall000** [comment]
Greetings placed by me **are quite suitable for their time**. I tried to mix them to avoid excessive repetition, for example 18, 19, 20, 21, 22 - good evening.. It's just boring))) "Добрый день" means not only the "afternoon", in this case in English it means something like "good day". None of the Russians this will not cause any questions:smirk:..

At the beta url - why names of the days of the week start with a small letter? (понедельник, вторник...). In my translation they start with a capital letter.

Hover hint text for links with a keyboard shortcut. = Текст всплывающей подсказки для ссылок с горячими клавишами.
"plugins.links.shortcutHint": "Нажмите {number} или кликните, чтобы открыть"
Hover hint text for links without a keyboard shortcut = Текст всплывающей подсказки для ссылок без горячих клавиш.
"plugins.links.standardHint": "Кликните для открытия"

I remembered that I forgot to translate the weather widget
**_\tabliss-master\src\plugins\widgets\weather\LocationInput.tsx_**
Search for city = Поиск по городу
Enter coordinates = Поиск по координатам
Latitude = Широта
Longitude = Долгота
Unable to determine your location = Не удалось определить ваше местоположение
Unable to determine location. Please try again later. = Не удалось определить местоположение. Пожалуйста, повторите попытку позже.

**_\tabliss-master\src\plugins\widgets\weather\Weather.tsx_**
Humidity = Влажность
Chance of rain = Вероятность осадков
```
rain/snow - осадки (on English google says it is - precipitation?(I do not know this word) )
or
rain = дождь (Вероятность дождя)
snow = снег (Вероятность выпадения снега)
```
Feels like 25° = Ощущается как 25°
Toggle weather details = Подробные данные о погоде

**_\tabliss-master\src\plugins\widgets\weather\WeatherSettings.tsx_**
Automatic units (based on location) = Автоматические единицы (по местоположению)
Metric units = Метрические единицы
Imperial units = Имперские единицы
Display on screen edge = Отображение на краю экрана
Powered by Dark Sky = При поддержке Dark Sky

**Comment by joelshepherd** [comment]
Thanks for the link hover translations!

I usually like to keep the greetings grouped together so they can give users a quick way to identify the time of day, especially when they don't have the time widget enabled. So "good morning" repeating a few times in the morning helps people subconsciously keep track of the time of day based on the greeting! If you can make a variant that does not return to a previous greeting after it has moved away (ie, A A B B is fine, but try not to do A B A B), I'll be happy to use that variant instead of mine!

The date localisation is actually handled by the library `react-intl` https://github.com/yahoo/react-intl. The small vs. capital letters on day and month name came from their locale data, and unfortunately, its something I cannot change.

I just realised I don't have translations for the weather widget, I'll need to add that soon!

**Comment by kristall000** [comment]
In the English version of greetings as I can see from 11 to 14 there is a "Hello". I'm not sure that it is possible for anyone to subconsciously understand what time it is now. But since it does exist, I added exactly the same greetings as "Hello": "Привет!", "Здравствуйте!", "Добро пожаловать". All this is a variation of "Hello". As I said earlier "Good afternoon" in EN = "Добрый день" in RU. We don't have this phrase, so "Добрый день" can means 10-18, not only 15-18. Based on this information, why not to mix variations of "Hello" and "Good afternoon" from 11 to 18, since in fact they mean the same thing?

Other phrases, such as "Приятных снов", "Пора спать", "Спокойной ночи"... are synonyms, which fit their intervals

Morning 5..10
Day 11..18
Evening 19..21
Time to sleep 22..4
According to all my greetings, these intervals can be determined without a clock, actually as you need it:
ABAB edited from the previous, which now for sure coincides with subconscious definition. I really will be happy if you accept this
0 = Приятных снов
1 = Пора спать
2 = Добро пожаловать в ночную смену
3= Доброй ночи
4 = Спокойной ночи
5 = Проснись и пой!
6 = Проснись и пой!
7 = Проснись и пой!
8= Доброе утро
9 = Доброе утро
10 = Прекрасного начала дня
11 = Добрый день
12 = Добро пожаловать
13 = Здравствуйте!
14 = Добрый день
15 = Добро пожаловать
16 = Привет!
17 = Добрый день
18 = Добро пожаловать
19 = Добрый вечер
20 = Добрый вечер
21 = Добрый вечер
22 = Доброй ночи
23 = Спокойной ночи

with name:
{greeting} = {greeting}, {name}
{greeting}! = {greeting}, {name}!

AABB, I'll never see "Доброй ночи" or maybe "Пора спать", but "Приятных снов" and "Спокойной ночи" take up all of my time :( exactly the same will happen to other phrases
0 = Приятных снов
1 = Приятных снов
2 = Пора спать
3= Доброй ночи
4 = Добро пожаловать в ночную смену
5 = Проснись и пой!
6 = Проснись и пой!
7 = Проснись и пой!
8= Доброе утро
9 = Доброе утро
10 = Прекрасного начала дня
11 = Добро пожаловать
12 = Добро пожаловать
13 = Здравствуйте!
14 = Здравствуйте!
15 = Добрый день
16 = Добрый день
17 = Привет!
18 = Привет!
19 = Добрый вечер
20 = Добрый вечер
21 = Добрый вечер
22 = Спокойной ночи
23 = Спокойной ночи

AABB An approximate match for the original. The most stripped-down version :C
0 = Приятных снов
1 = Приятных снов
2 = Приятных снов
3= Проснись и пой!
4 = Проснись и пой!
5 = Проснись и пой!
6 = Доброе утро
7 = Доброе утро
8= Доброе утро
9 = Доброе утро
10 = Привет!
11 = Привет!
12 = Привет!
13 = Привет!
14 = Добрый день
15 = Добрый день
16 = Добрый день
17 = Добрый день
18 = Добрый вечер
19 = Добрый вечер
20 = Добрый вечер
21 = Добрый вечер
22 = Спокойной ночи
23 = Спокойной ночи

You are the developer and of course you decide

**Comment by kristall000** [comment]
That's what I still wanted to ask, please add an icon to the quick links, like the picture below,
it's logo of [vk.com](https://vk.com)
[Here you can take psd & eps](https://vk.com/page-550910_46759154) / [PSD](https://vk.com/doc75344642_449888252) & [EPS](https://vk.com/doc75344642_449888239)
Or tell me what sizes of pictures are needed, I'll send you a png
![vk_logo](https://user-images.githubusercontent.com/13225484/42411005-9016d2be-81fc-11e8-8287-250a1ae1f2a2.png)

**Comment by joelshepherd** [comment]
Hey, I have ended up going with your first (and your preferred) option for the greetings. I'll be releasing the next version of Tabliss, with the translations (and search engines) in the next few days!

For the quick links logo, the current list of icons comes from here: https://github.com/feathericons/feather
So to bring the vk icon into Tabliss, you will need to request the icon there. Having said that, I do hope to bring custom quick link icons in as a future Tabliss feature 👌 

Thanks for all your hard work getting these features in!

**Comment by joelshepherd** [comment]
As the main features in this issue are complete, I am closing this issue.

For the VK icon, aside from getting it upstream in Feather Icons, I'll track that feature in #34.
