### ISSUE TITLE
Set the options somewhere else.

### ISSUE THREAD

**Issue by jraspiprojects** [joelshepherd/tabliss#63]
For example, on chrome if you click the tabliss icon, you get the settings.

The options' location will be customizable if you want them in the same old postition or in the new one.

**Comment by joelshepherd** [comment]
Hey sorry for being a bit late to this - but I am not exactly sure what you are asking.

I'm closing this for now, but if you can explain it, maybe with a screenshot or so, I will be happy to re-open.
