### ISSUE TITLE
unable to load localhost url in the widget "quick links"

### ISSUE THREAD

**Issue by GitEin11** [joelshepherd/tabliss#630]
unable to load url like localhost:8080 in quick links with mouse left key, only works with open on new tab i.e. middle button click
This happens on windows 10, but it works fine on linux

**Comment by the-wright-jamie** [comment]
What browser are you using?

Currently working fine on Chrome `116.0.5845.140` on ARM macOS `13.5.1`.

**Comment by GitEin11** [comment]
Firefox 117.0 (64-bit) on Win 10, when using left mouse click it reloads tabliss insteads of loading the localhost, middle click works since it opens as newtab

**Comment by the-wright-jamie** [comment]
Does your URL look like this:
![image](https://github.com/joelshepherd/tabliss/assets/121819290/027fc82b-0d82-4ab7-b0ae-7893e4d27991)

or this:
![image](https://github.com/joelshepherd/tabliss/assets/121819290/dcc28787-fbdf-476e-a8ef-6d73c7fe3858)

The second one works for me, the first doesn't.

**Comment by GitEin11** [comment]
thanks, http://localhost:8080 works
