### ISSUE TITLE
Daily Quotes aren't showing

### ISSUE THREAD

**Issue by MustaDevelop** [joelshepherd/tabliss#637]
Hello! I've been trying to get some Funny Quotes, but it didn't show up. I'm 100% sure it wasn't the Display Settings because Developer Excuses does shows up. And even if I wait a day it doesn't show up.

Funny Quotes (or any Daily Quotes):
![firefox_E9y4187rhp](https://github.com/joelshepherd/tabliss/assets/77793061/8296f413-e3d6-487f-a473-dbd5db8f2264)

Developer Excuses:
![firefox_lEvfKLv22q](https://github.com/joelshepherd/tabliss/assets/77793061/1e2954cd-033a-4e47-9415-5e8a6e37a3ab)

**Comment by the-wright-jamie** [comment]
Hi! Nice setup!

See these issues as to why it's not working:
- https://github.com/joelshepherd/tabliss/issues/601
- https://github.com/joelshepherd/tabliss/issues/614

I 'fixed' this in my fork (I removed the option for Daily Quotes, but I plan the ability to add your own quotes):
- https://github.com/the-wright-jamie/tab-nine/issues/29
- https://github.com/the-wright-jamie/tab-nine/issues/80

If you'd like to contribute, I'm actively watching for PRs - I haven't seen anything from this project in 4 months and the last build was from over a year ago.

**Comment by MustaDevelop** [comment]
> If you'd like to contribute, I'm actively watching for PRs - I haven't seen anything from this project in 4 months and the last build was from over a year ago.

Over a year? Wow, that's just sad.

**Comment by the-wright-jamie** [comment]
It's certainly unfortunate, it's a very good project and the original developer was very smart - a lot of really interesting and clever things in here. The main problem is the lack of automated releases, but I suppose that wouldn't matter due to the lack of other team members with write access interacting with the project.
