### ISSUE TITLE
[Suggestion] Date format

### ISSUE THREAD

**Issue by EloItsMee** [joelshepherd/tabliss#64]
Love the add-on, but just one tiny niggle; the ability to change the date format would be useful for us non-Americans.

Currently the date format is 'Day, Month Date', but I would love to change it to 'Day, Date Month'. 
Even better would be to tweak the date format as we see fit using something similar to Python's 'strftime' (although obviously not strftime itself, as your add-on isn't Python-based).

**Comment by joelshepherd** [comment]
Hey!

Thanks for the feedback. The date format is determined by the locale set (the language toggle). If you swap languages, you'll notice the date format rearranges depending on the default for the locale.

Having said that, it has just occurred to me now that English defaults to US English and date format, which as an Australian (whose date format is actually the one you are requesting), I can't believe I missed! I'll add in UK and AU English variations to the language switcher so you can have the date in the format you desire!

**Comment by joelshepherd** [comment]
Now released!
