### ISSUE TITLE
[Feature Request] Add option to use system wallpaper as background

### ISSUE THREAD

**Issue by ghost** [joelshepherd/tabliss#646]
If one just changes their system wallpaper (whether they're using Linux, Mac or Windows) which many people do frequently their tabliss background also changes, like the Opera browser has an option for it's new tab page. Since the tabliss extension would be using the same background as the system, this would make the system more coherent as the system's desktop and browser would be using the same wallpaper.

**Comment by Secret-chest** [comment]
It's not possible for a browser extension to access files not uploaded.

**Comment by ghost** [comment]
> It's not possible for a browser extension to access files not uploaded.

Do you have a source for this information or are you an extension dev?

**Comment by Secret-chest** [comment]
It is very complex to do this.
