### ISSUE TITLE
[Feature Request] Display Firefox snippets

### ISSUE THREAD

**Issue by HannanAkbar** [joelshepherd/tabliss#68]
It would be nice to give an option to display Firefox snippets at the bottom. Sometimes they contain a useful piece of info.

**Comment by joelshepherd** [comment]
Hey, I have had a bit of a look into this. It seems to be a touch tricky to do, but it is technically possible.

That said, it is probably not something I am looking to implement at this time. However, if this issue gains traction in the future, I will reconsider dedicating time to getting it working. Thanks!
