### ISSUE TITLE
Option to add Links to a new Tab

### ISSUE THREAD

**Issue by schannall** [joelshepherd/tabliss#7]
In Momentum on Chrome (https://chrome.google.com/webstore/detail/momentum/laookkfknpbbblfpciffpaejjkokdgca) you can add a list of links that is shown when you mouse over an Icon or text. It would be great if you could add something like that to tabliss as well.

BTW: Thanks for tabliss, it is what I was searching for on FF.

**Comment by joelshepherd** [comment]
Hi! I agree, a links widget would be a really useful addition.
I'll add it to my plan for the next widget 👍

**Comment by joelshepherd** [comment]
Hi, I have completed the first version of the Quick Links widget for Tabliss! You should be able to see it in the next few days once your browser updates Tabliss :)

**Comment by schannall** [comment]
Hi Great, thank you. 
Could I request two more things?
a) Make it possible to have the links appear not in the middle but in one of the corners
b) Make renaming links possible

Regards,
Jonas

**Comment by joelshepherd** [comment]
I have added the option for renaming (will be available in next release). Moving any/all widgets is planned for a future release :)
