### ISSUE TITLE
No way to find settings in Firefox

### ISSUE THREAD

**Issue by drazisil** [joelshepherd/tabliss#74]
=== Issue ===
There appears to be no way to access settings on Firefox. I have no icon, and no preferences or options button in the extensions list.

=== Expected Results ===
If this is here and I'm overlooking it, if it could be documented how to access it that would be helpful.

=== Details ===
Tabliss Version: 1.14.0
Browser version: Firefox 61.0.1 (64-bit)
OS: Debian Stretch

**Comment by drazisil** [comment]
Located it. Gear in the top left of the new tab page. Closing issue.

**Comment by Dantusaikamal** [comment]
> I seem to have this problem too. I'm not sure why because I didn't before (?). Where is the Gear located? Help Please.
> Thank you

I know it's been 3 whole years. If anyone is still unable to find the gear icon, it's below the back, reload, reload buttons :)
![1](https://user-images.githubusercontent.com/65682028/122174074-0a6df680-cea0-11eb-8620-d2a46d3b116b.png)

**Comment by K1LL3RPUNCH** [comment]
> 
> 
> > I seem to have this problem too. I'm not sure why because I didn't before (?). Where is the Gear located? Help Please.
> > Thank you
> 
> I know it's been 3 whole years. If anyone is still unable to find the gear icon, it's below the back, reload buttons :)
> ![1](https://user-images.githubusercontent.com/65682028/122174074-0a6df680-cea0-11eb-8620-d2a46d3b116b.png)

damn, it took 2 hours for me to find this little gear. thank you :)
