### ISSUE TITLE
[Feature request] Ability to change font settings for the text in bottom left and right corners

### ISSUE THREAD

**Issue by odebroqueville** [joelshepherd/tabliss#76]
I would very much like to be able to change the font family and colour of the text in the bottom left and right hand corners so that it is more like the placeholder for searches, i.e. a discrete grey instead of bright white. I'm finding that white stands out too much.
![screen shot 2018-07-15 at 12 15 29](https://user-images.githubusercontent.com/4818315/42732896-bb09767e-8829-11e8-9205-b709b5682f85.jpg)

**Comment by trickypr** [comment]
You can do this using the custom css widget. 
```css
.credit, .summary, .Overlay {
  color: grey;
  font-family: serif;
}
```
This code changes the text color to grey and the font family to serif.

**Comment by joelshepherd** [comment]
Yep @trickypr's solution should work. You can also use `opacity: 0.5` instead of `color: grey`, if that's more your style.

Since those items are part of the background plugin, not widgets, they don't respect the styling of the font settings widget. Maybe that's something I could change.

**Comment by odebroqueville** [comment]
@trickypr @joelshepherd Thanks to both of you. I have tested the following:
.credit {
  opacity: 0.4;
  font-family: inherit;
}
.credit a:hover {
  opacity: 1.0;
}
But for some reason, hovering over the text doesn't do anything! Would you happen to know what I'm doing wrong?
