### ISSUE TITLE
How do you format code?

### ISSUE THREAD

**Issue by vorou** [joelshepherd/tabliss#79]
How do you format code? I noticed you use some uncommon formatting rules (like putting a whitespace after `!`). Do you do it manually, or do you use a code reformatter like [prettier](https://github.com/prettier/prettier) w/ a custom config?

keywords: prettier, code reformat, code style, beautifier

**Comment by joelshepherd** [comment]
That's a good question. I guess I just manually follow along with the linter (the default from the TypeScript `create-react-app`) plus some other stylistic opinions from my favourite style guide (airbnb) and previous languages.

For bang-space (`! `) specifically, that's a carry over of one of my favourite style rules from Laravel.
