### ISSUE TITLE
Problem with latest version on firefox

### ISSUE THREAD

**Issue by bitboxer** [joelshepherd/tabliss#8]
Sadly I only see a black page. It started a couple of days ago and today I found time to have a short
look.

The dev console outputs this:

```
TypeError: t is undefined [Learn More] 
main.134b549c6442.js:5:16771
```

If you need any help debugging this, just say what you need and I will try to help.

**Comment by joelshepherd** [comment]
Hi, thanks for reporting this.

It appears Tabliss is running into an error when it tries to retrieve your saved settings from storage. It may be your local `IndexedDB` database has become corrupted. Though I am not sure what could of caused that.

Can you see if deleting the Tabliss `IndexedDB` database clears up your issue? I just added some instructions at the bottom of here for how to do it: https://tabliss.io/support.html

If it solves your issue I'll need to them go investigate how I could corrupt the data store 🤔, or come up with a graceful recovery at least!

**Comment by bitboxer** [comment]
Thanks. That helped. My firefox crashed the other day and I had to reboot my mac to get it working again. Maybe that also caused the indexdb to be corrupted.

**Comment by Smile4ever** [comment]
@joelshepherd I think this can be closed.
