### ISSUE TITLE
[Feature request] Ability to contorl homepage

### ISSUE THREAD

**Issue by Mraru** [joelshepherd/tabliss#81]
In the latest version this plugin has no longer to control brower's homepage. But I really like a beautiful picture instead of the default white homepage. 
So can you considing to make this feature available as an options in future?

**Comment by Mraru** [comment]
Sorry I just found this option in buttom. I will close this issue.

Whatever, this plugin is great and thanks to your work.

**Comment by joelshepherd** [comment]
Hi! Yep, I added that after I removed the homepage control. Now I think about it I should probably have made the button a bit more obvious. 🤔
