### ISSUE TITLE
Blob prevents being able to save fav backgrounds

### ISSUE THREAD

**Issue by bakaoniisan** [joelshepherd/tabliss#83]
A minor whinge. I kind of feel bad for pointing it out

The new 1.15 uses js blob for images and I can no longer save them

I personally save favourite backgrounds because my desktop does random backgrounds.

I'm using the latest Firefox

**Comment by joelshepherd** [comment]
How are you trying to save them?

And do you mean for Unsplash backgrounds? If so, you can click on the word "Photo" in the bottom left corner to visit Unsplash and download them in full resolution!

**Comment by joelshepherd** [comment]
Yeah I should probably make that link a bit more obvious! But no problem, I'm glad you are enjoying Tabliss!
