### ISSUE TITLE
JS example

### ISSUE THREAD

**Issue by Bookrage001** [joelshepherd/tabliss#89]
Does someone have an example of some js code that i could build off of ?

**Comment by joelshepherd** [comment]
Hey, there is currently a bug blocking custom scripts from running (see #90). Once this is resolved I will put together an example or two!

Slightly off topic: I have been thinking about creating a gallery/repository somewhere of some of the cool custom CSS and JS snippets that people have made. Could be fun 😄

**Comment by Arcandres** [comment]
I have this code to add favicons to links but I can't implement it :( 
```js
const links = document.querySelectorAll('.Links a')
let i = links.length

while(i--) {
  links[i].style.background = `url(https://www.google.com/s2/favicons?domain=${links[i].href.match(/:\/\/(.[^\/\?]+)/)[1]}) no-repeat left center`
  links[i].style.paddingLeft = '1.2rem'
}
```

**Comment by joelshepherd** [comment]
Hey @Arcandres, check issue #90 for progress on solving the custom JS issue.
