### ISSUE TITLE
Use Firefox Home Page Pinned Links for Quick Links

### ISSUE THREAD

**Issue by AmrEldib** [joelshepherd/tabliss#98]
Firefox has a key in the configuration for pinned links in the home page `browser.newtabpage.pinned`. I'm not sure if extensions have access to it or not, but it would be great to use those quick links instead of having to enter them again.

**Comment by Smile4ever** [comment]
I believe that's called https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/topSites

**Comment by joelshepherd** [comment]
I'll track this in #10 instead
